//
//  FrameName.swift
//  SwiftTagger_MacOS
//
//  Created by Nolaine Crusher on 4/8/20.
//  Copyright © 2020 Nolaine Crusher. All rights reserved.
//

import Foundation

enum FrameName: String {
    
    case album = "Album"
    case albumSort = "Sort Album"
    case albumArtist = "Album Artist"
    case albumArtistSort = "Sort Album Artist"
    case arranger = "Arranger, or Remixer"
    case artist = "Artist"
    case artistSort = "Sort Artist"
    case artistWebpage = "Artist Webpage"
    case attachedPicture = "Attached Picture"
    case audioFileWebpage = "Audio File Webpage"
    case audioSourceWebpage = "Audio Source Webpage"
    case bpm = "BPM"
    case chapter = "CHAP"
    case comments = "Comments"
    case compilation = "Compilation"
    case composer = "Composer"
    case composerSort = "Sort Composer"
    case conductor = "Conductor"
    case contentGroup = "Work or Content Group"
    case copyright = "Copyright"
    case copyrightWebpage = "Copyright Info Webpage"
    case date = "Date"
    case discNumber = "Disc Number (of Total)"
    case encodingTime = "Encoding Time"
    case encodedBy = "encoded By"
    case encodingSettings = "Encoder Settings"
    case fileType = "File Type"
    case fileOwner = "File Owner"
    case genre = "Genre"
    case grouping = "Grouping"
    case initialKey = "Initial Key"
    case involvedPeopleList = "Involved People List"
    case isrc = "ISRC"
    case languages = "Language"
    case length = "Length"
    case lyricist = "Lyricist"
    case mediaType = "Media Type"
    case mood = "Mood"
    case movementCount = "Movement Count"
    case movementName = "Movement Name"
    case movementNumber = "Movement Number"
    case musicianCreditsList = "Musician Credits List"
    case originalAlbum = "Original Album"
    case originalArtist = "Original Artist"
    case originalFilename = "Original Filename"
    case originalLyricist = "Original Lyricist"
    case originalReleaseTime = "Original Release Time"
    case paymentWebpage = "Payment Webpage"
    case playlistDelay = "Playlist Delay"
    case podcastCategory = "Podcast Category"
    case podcastDescription = "Podcast Description"
    case podcastID = "Podcast ID"
    case podcastKeywords = "Podcast Keywords"
    case podcastFeedLink = "Podcast Link"
    case producedNotice = "Produced Notice"
    case publisher = "Publisher"
    case publisherWebpage = "Publisher Webpage"
    case radioStation = "Internet Radio Station Name"
    case radioStationOwner = "Internet Radio Station Owner"
    case radioStationWebpage = "Internet Radio Station Webpage"
    case recordingDate = "Recording Date"
    case releaseTime = "Release Time"
    case setSubtitle = "Set Subtitle"
    case subtitle = "Subtitle"
    case tableOfContents = "Table of Contents"
    case taggingTime = "Tagging Time"
    case time = "Time"
    case title = "Title"
    case titleSort = "Sort Title"
    case trackNumber = "Track Number (of Total)"
    case unsynchronizedLyrics = "Unsynced Lyrics"
    case userDefinedText = "User Defined Text Information"
    case userDefinedWebpage = "User Defined Webpage"
    case year = "Year"

}
