//
//  FrameName.swift
//  SwiftTagger_MacOS
//
//  Created by Nolaine Crusher on 4/8/20.
//  Copyright © 2020 Nolaine Crusher. All rights reserved.
//

import Foundation

/** FrameName describes how SwiftTagger refers to the frame type internally. All information, such as ParserType, FrameType, the ID3FrameIdentifier, */
enum FrameName: String {
    
    case album = "Album"
    case albumSort = "SortAlbum"
    case albumArtist = "AlbumArtist"
    case albumArtistSort = "SortAlbumArtist"
    case arranger = "Arranger"
    case artist = "Artist"
    case artistSort = "SortArtist"
    case artistWebpage = "ArtistWebpage"
    case attachedPicture = "AttachedPicture"
    case audioFileWebpage = "AudioFileWebpage"
    case audioSourceWebpage = "AudioSourceWebpage"
    case bpm = "BPM"
    case chapter = "Chapter"
    case comments = "Comments"
    case compilation = "Compilation"
    case composer = "Composer"
    case composerSort = "SortComposer"
    case conductor = "Conductor"
    case contentGroup = "Work"
    case copyright = "Copyright"
    case copyrightWebpage = "CopyrightInfoWebpage"
    case date = "Date"
    case discNumber = "DiscNumberOfTotal"
    case encodingTime = "EncodingTime"
    case encodedBy = "encoded By"
    case encodingSettings = "EncoderSettings"
    case fileType = "FileType"
    case fileOwner = "FileOwner"
    case genre = "Genre"
    case grouping = "Grouping"
    case initialKey = "InitialKey"
    case involvedPeopleList = "InvolvedPeopleList"
    case isrc = "ISRC"
    case languages = "Language"
    case length = "Length"
    case lyricist = "Lyricist"
    case mediaType = "MediaType"
    case mood = "Mood"
    case movementCount = "MovementCount"
    case movementName = "MovementName"
    case movementNumber = "MovementNumber"
    case musicianCreditsList = "MusicianCreditsList"
    case originalAlbum = "OriginalAlbum"
    case originalArtist = "OriginalArtist"
    case originalFilename = "OriginalFilename"
    case originalLyricist = "OriginalLyricist"
    case originalReleaseTime = "OriginalReleaseTime"
    case paymentWebpage = "PaymentWebpage"
    case playlistDelay = "PlaylistDelay"
    case podcastCategory = "PodcastCategory"
    case podcastDescription = "PodcastDescription"
    case podcastID = "PodcastID"
    case podcastKeywords = "PodcastKeywords"
    case podcastFeedLink = "PodcastLink"
    case producedNotice = "ProducedNotice"
    case publisher = "Publisher"
    case publisherWebpage = "PublisherWebpage"
    case radioStation = "InternetRadioStationName"
    case radioStationOwner = "InternetRadioStationOwner"
    case radioStationWebpage = "InternetRadioStationWebpage"
    case recordingDate = "RecordingDate"
    case releaseTime = "ReleaseTime"
    case setSubtitle = "SetSubtitle"
    case subtitle = "Subtitle"
    case tableOfContents = "TableOfContents"
    case taggingTime = "TaggingTime"
    case time = "Time"
    case title = "Title"
    case titleSort = "SortTitle"
    case trackNumber = "TrackNumberOfTotal"
    case unsynchronizedLyrics = "UnsyncedLyrics"
    case userDefinedText = "UserDefinedTextInformation"
    case userDefinedWebpage = "UserDefinedWebpage"
    case year = "Year"

}
