//
//  ContentRatings.swift
//  SwiftTagger_MacOS
//
//  Created by Nolaine Crusher on 4/30/20.
//  Copyright © 2020 Nolaine Crusher. All rights reserved.
//

import Foundation

public struct ContentRatings {
    public let country: String
    public let media: String
    public let prefix: String
    public let iTunesCode: String
    public let iTunesValue: String
    public let description: String
    
    var ratings: String {
        for rating in RatingsInfo.ratings {
            return "\(rating.prefix)|\(rating.iTunesCode)|\(rating.iTunesValue)|"
        }; return ""
    }
}

struct RatingsInfo {
    static let ratings: [ContentRatings] = [
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "NR", iTunesValue: "000", description: "NR"),
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "PG-13", iTunesValue: "300", description: "PG-13"),
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "R", iTunesValue: "400", description: "R"),
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "NC-17", iTunesValue: "500", description: "NC-17"),
        ContentRatings(country: "USA", media: "Movie", prefix: "mpaa", iTunesCode: "unrated", iTunesValue: "???", description: "unrated"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "TV-Y", iTunesValue: "100", description: "TV-Y"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "TV-Y7", iTunesValue: "200", description: "TV-Y7"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "TV-G", iTunesValue: "300", description: "TV-G"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "TV-PG", iTunesValue: "400", description: "TV-PG"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "TV-14", iTunesValue: "500", description: "TV-14"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "TV-MA", iTunesValue: "600", description: "TV-MA"),
        ContentRatings(country: "USA", media: "TV", prefix: "us-tv", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "Australia", media: "Movie", prefix: "au-movie", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "Australia", media: "Movie", prefix: "au-movie", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "Australia", media: "Movie", prefix: "au-movie", iTunesCode: "M", iTunesValue: "350", description: "M"),
        ContentRatings(country: "Australia", media: "Movie", prefix: "au-movie", iTunesCode: "MA15+", iTunesValue: "375", description: "MA15+"),
        ContentRatings(country: "Australia", media: "Movie", prefix: "au-movie", iTunesCode: "R18+", iTunesValue: "400", description: "R18+"),
        ContentRatings(country: "Australia", media: "Movie", prefix: "au-movie", iTunesCode: "Not Rated", iTunesValue: "???", description: "Not Rated"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "P", iTunesValue: "100", description: "P"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "C", iTunesValue: "200", description: "C"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "G", iTunesValue: "300", description: "G"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "PG", iTunesValue: "400", description: "PG"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "M", iTunesValue: "500", description: "M"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "MA15+", iTunesValue: "550", description: "MA15+"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "AV15+", iTunesValue: "575", description: "AV15+"),
        ContentRatings(country: "Australia", media: "TV", prefix: "au-tv", iTunesCode: "R18+", iTunesValue: "160", description: "R18+"),
        ContentRatings(country: "Brasil", media: "Movie", prefix: "br-movie", iTunesCode: "L", iTunesValue: "000", description: "L"),
        ContentRatings(country: "Brasil", media: "Movie", prefix: "br-movie", iTunesCode: "12", iTunesValue: "100", description: "12"),
        ContentRatings(country: "Brasil", media: "Movie", prefix: "br-movie", iTunesCode: "14", iTunesValue: "300", description: "14"),
        ContentRatings(country: "Brasil", media: "Movie", prefix: "br-movie", iTunesCode: "16", iTunesValue: "350", description: "16"),
        ContentRatings(country: "Brasil", media: "Movie", prefix: "br-movie", iTunesCode: "18", iTunesValue: "400", description: "18"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "14A", iTunesValue: "300", description: "14A"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "18A", iTunesValue: "350", description: "18A"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "R", iTunesValue: "400", description: "R"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "A", iTunesValue: "500", description: "A"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "Canada", media: "Movie", prefix: "ca-movie", iTunesCode: "Not Rated", iTunesValue: "???", description: "Not Rated"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "E", iTunesValue: "000", description: "E"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "C", iTunesValue: "050", description: "C"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "C8", iTunesValue: "075", description: "C8"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "14+", iTunesValue: "300", description: "14+"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "18+", iTunesValue: "350", description: "18+"),
        ContentRatings(country: "Canada", media: "TV", prefix: "ca-tv", iTunesCode: "21+", iTunesValue: "500", description: "21+"),
        ContentRatings(country: "Deutschland", media: "Movie", prefix: "de-movie", iTunesCode: "Ab 0 Jahren", iTunesValue: "075", description: "Ab 0 Jahren"),
        ContentRatings(country: "Deutschland", media: "Movie", prefix: "de-movie", iTunesCode: "Ab 6 Jahren", iTunesValue: "100", description: "Ab 6 Jahren"),
        ContentRatings(country: "Deutschland", media: "Movie", prefix: "de-movie", iTunesCode: "Ab 12 Jahren", iTunesValue: "200", description: "Ab 12 Jahren"),
        ContentRatings(country: "Deutschland", media: "Movie", prefix: "de-movie", iTunesCode: "Ab 16 Jahren", iTunesValue: "500", description: "Ab 16 Jahren"),
        ContentRatings(country: "Deutschland", media: "Movie", prefix: "de-movie", iTunesCode: "Ab 18 Jahren", iTunesValue: "600", description: "Ab 18 Jahren"),
        ContentRatings(country: "Deutschland", media: "TV", prefix: "de-tv", iTunesCode: "Ab 0 Jahren", iTunesValue: "075", description: "Ab 0 Jahren"),
        ContentRatings(country: "Deutschland", media: "TV", prefix: "de-tv", iTunesCode: "Ab 6 Jahren", iTunesValue: "100", description: "Ab 6 Jahren"),
        ContentRatings(country: "Deutschland", media: "TV", prefix: "de-tv", iTunesCode: "Ab 12 Jahren", iTunesValue: "200", description: "Ab 12 Jahren"),
        ContentRatings(country: "Deutschland", media: "TV", prefix: "de-tv", iTunesCode: "Ab 16 Jahren", iTunesValue: "500", description: "Ab 16 Jahren"),
        ContentRatings(country: "Deutschland", media: "TV", prefix: "de-tv", iTunesCode: "Ab 18 Jahren", iTunesValue: "600", description: "Ab 18 Jahren"),
        ContentRatings(country: "France", media: "Movie & TV", prefix: "fr-movie", iTunesCode: "Tout public", iTunesValue: "000", description: "Tout public"),
        ContentRatings(country: "France", media: "Movie & TV", prefix: "fr-movie", iTunesCode: "-10", iTunesValue: "100", description: "-10"),
        ContentRatings(country: "France", media: "Movie & TV", prefix: "fr-movie", iTunesCode: "-12", iTunesValue: "300", description: "-12"),
        ContentRatings(country: "France", media: "Movie & TV", prefix: "fr-movie", iTunesCode: "-16", iTunesValue: "375", description: "-16"),
        ContentRatings(country: "France", media: "Movie & TV", prefix: "fr-movie", iTunesCode: "-18", iTunesValue: "400", description: "-18"),
        ContentRatings(country: "France", media: "Movie & TV", prefix: "fr-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "Italia", media: "Movie", prefix: "it-movie", iTunesCode: "T", iTunesValue: "100", description: "T"),
        ContentRatings(country: "Italia", media: "Movie", prefix: "it-movie", iTunesCode: "VPA", iTunesValue: "125", description: "VPA"),
        ContentRatings(country: "Italia", media: "Movie", prefix: "it-movie", iTunesCode: "VM10", iTunesValue: "150", description: "VM10"),
        ContentRatings(country: "Italia", media: "Movie", prefix: "it-movie", iTunesCode: "VM12", iTunesValue: "200", description: "VM12"),
        ContentRatings(country: "Italia", media: "Movie", prefix: "it-movie", iTunesCode: "VM14", iTunesValue: "325", description: "VM14"),
        ContentRatings(country: "Italia", media: "Movie", prefix: "it-movie", iTunesCode: "VM18", iTunesValue: "400", description: "VM18"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "Not Rated", iTunesValue: "000", description: "Not Rated"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "12", iTunesValue: "300", description: "12"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "15", iTunesValue: "350", description: "15"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "16", iTunesValue: "375", description: "16"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "18", iTunesValue: "400", description: "18"),
        ContentRatings(country: "Ireland", media: "Movie", prefix: "ie-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "Ireland", media: "TV", prefix: "ie-tv", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "Ireland", media: "TV", prefix: "ie-tv", iTunesCode: "PG", iTunesValue: "350", description: "PG"),
        ContentRatings(country: "Ireland", media: "TV", prefix: "ie-tv", iTunesCode: "12", iTunesValue: "400", description: "12"),
        ContentRatings(country: "Ireland", media: "TV", prefix: "ie-tv", iTunesCode: "15", iTunesValue: "500", description: "15"),
        ContentRatings(country: "Ireland", media: "TV", prefix: "ie-tv", iTunesCode: "18", iTunesValue: "600", description: "18"),
        ContentRatings(country: "日本", media: "Movie", prefix: "jp-movie", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "日本", media: "Movie", prefix: "jp-movie", iTunesCode: "PG12", iTunesValue: "200", description: "PG12"),
        ContentRatings(country: "日本", media: "Movie", prefix: "jp-movie", iTunesCode: "R15+", iTunesValue: "300", description: "R15+"),
        ContentRatings(country: "日本", media: "Movie", prefix: "jp-movie", iTunesCode: "R18+", iTunesValue: "400", description: "R18+"),
        ContentRatings(country: "日本", media: "Movie", prefix: "jp-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "未審査"),
        ContentRatings(country: "Mexico", media: "Movie", prefix: "mx-movie", iTunesCode: "AA", iTunesValue: "000", description: "AA"),
        ContentRatings(country: "Mexico", media: "Movie", prefix: "mx-movie", iTunesCode: "A", iTunesValue: "100", description: "A"),
        ContentRatings(country: "Mexico", media: "Movie", prefix: "mx-movie", iTunesCode: "B", iTunesValue: "300", description: "B"),
        ContentRatings(country: "Mexico", media: "Movie", prefix: "mx-movie", iTunesCode: "B-15", iTunesValue: "500", description: "B-15"),
        ContentRatings(country: "Mexico", media: "Movie", prefix: "mx-movie", iTunesCode: "C", iTunesValue: "600", description: "C"),
        ContentRatings(country: "Nederland", media: "Movie & TV", prefix: "nl-movie", iTunesCode: "AL/G", iTunesValue: "000", description: "AL/G"),
        ContentRatings(country: "Nederland", media: "Movie & TV", prefix: "nl-movie", iTunesCode: "6", iTunesValue: "100", description: "6"),
        ContentRatings(country: "Nederland", media: "Movie & TV", prefix: "nl-movie", iTunesCode: "9", iTunesValue: "200", description: "9"),
        ContentRatings(country: "Nederland", media: "Movie & TV", prefix: "nl-movie", iTunesCode: "12", iTunesValue: "300", description: "12"),
        ContentRatings(country: "Nederland", media: "Movie & TV", prefix: "nl-movie", iTunesCode: "16", iTunesValue: "500", description: "16"),
        ContentRatings(country: "Nederland", media: "Movie & TV", prefix: "nl-movie", iTunesCode: "18", iTunesValue: "600", description: "18"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "M", iTunesValue: "300", description: "M"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "R13", iTunesValue: "325", description: "R13"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "RP13", iTunesValue: "325", description: "RP13"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "R15", iTunesValue: "350", description: "R15"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "R16", iTunesValue: "375", description: "R16"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "RP16", iTunesValue: "375", description: "RP16"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "R18", iTunesValue: "400", description: "R18"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "R", iTunesValue: "500", description: "R"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "U", iTunesValue: "900", description: "U"),
        ContentRatings(country: "New Zealand", media: "Movie & TV", prefix: "nz-movie", iTunesCode: "Not Rated", iTunesValue: "???", description: "Not Rated"),
        ContentRatings(country: "Sverige", media: "Movie & TV", prefix: "se-movie", iTunesCode: "A", iTunesValue: "000", description: "Barntillåten"),
        ContentRatings(country: "Sverige", media: "Movie & TV", prefix: "se-movie", iTunesCode: "7", iTunesValue: "125", description: "Från 7 år"),
        ContentRatings(country: "Sverige", media: "Movie & TV", prefix: "se-movie", iTunesCode: "11", iTunesValue: "225", description: "Från 11 år"),
        ContentRatings(country: "Sverige", media: "Movie & TV", prefix: "se-movie", iTunesCode: "15", iTunesValue: "400", description: "Från 15 år"),
        ContentRatings(country: "Sverige", media: "Movie & TV", prefix: "se-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Ocensurerad"),
        ContentRatings(country: "Sverige", media: "Movie & TV", prefix: "se-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Inte klassificerad"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "0", iTunesValue: "050", description: "0"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "6", iTunesValue: "075", description: "6"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "7", iTunesValue: "125", description: "7"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "10", iTunesValue: "150", description: "10"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "12", iTunesValue: "200", description: "12"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "14", iTunesValue: "325", description: "14"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "16", iTunesValue: "375", description: "16"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "18", iTunesValue: "400", description: "18"),
        ContentRatings(country: "Schweiz", media: "Movie", prefix: "ch-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "keine alterseinstufung"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "0", iTunesValue: "050", description: "0"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "6", iTunesValue: "075", description: "6"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "7", iTunesValue: "125", description: "7"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "10", iTunesValue: "150", description: "10"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "12", iTunesValue: "200", description: "12"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "14", iTunesValue: "325", description: "14"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "16", iTunesValue: "375", description: "16"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "18", iTunesValue: "400", description: "18"),
        ContentRatings(country: "Suisse", media: "Movie", prefix: "ch-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "keine alterseinstufung"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "NR", iTunesValue: "000", description: "Not Rated"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "U", iTunesValue: "100", description: "U"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "Uc", iTunesValue: "150", description: "Uc"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "PG", iTunesValue: "200", description: "PG"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "12", iTunesValue: "300", description: "12"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "12A", iTunesValue: "325", description: "12A"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "15", iTunesValue: "350", description: "15"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "18", iTunesValue: "400", description: "18"),
        ContentRatings(country: "UK", media: "TV", prefix: "uk-tv", iTunesCode: "Caution", iTunesValue: "500", description: "Caution"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "R18", iTunesValue: "600", description: "R18"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "E", iTunesValue: "0", description: "Exempt"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "UK", media: "Movie & TV", prefix: "uk-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "TBC"),
        ContentRatings(country: "Россия", media: "Movie & TV", prefix: "ru-movie", iTunesCode: "0+", iTunesValue: "000", description: "0+"),
        ContentRatings(country: "Россия", media: "Movie & TV", prefix: "ru-movie", iTunesCode: "6+", iTunesValue: "150", description: "6+"),
        ContentRatings(country: "Россия", media: "Movie & TV", prefix: "ru-movie", iTunesCode: "12+", iTunesValue: "200", description: "12+"),
        ContentRatings(country: "Россия", media: "Movie & TV", prefix: "ru-movie", iTunesCode: "16+", iTunesValue: "375", description: "16+"),
        ContentRatings(country: "Россия", media: "Movie & TV", prefix: "ru-movie", iTunesCode: "18+", iTunesValue: "400", description: "18+"),
        ContentRatings(country: "Россия", media: "Movie & TV", prefix: "ru-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "Pilipinas", media: "Movie & TV", prefix: "ph-movie", iTunesCode: "G", iTunesValue: "100", description: "G"),
        ContentRatings(country: "Pilipinas", media: "Movie & TV", prefix: "ph-movie", iTunesCode: "PG", iTunesValue: "300", description: "PG"),
        ContentRatings(country: "Pilipinas", media: "Movie & TV", prefix: "ph-movie", iTunesCode: "R-13", iTunesValue: "325", description: "R-13"),
        ContentRatings(country: "Pilipinas", media: "Movie & TV", prefix: "ph-movie", iTunesCode: "R-16", iTunesValue: "375", description: "R-16"),
        ContentRatings(country: "Pilipinas", media: "Movie & TV", prefix: "ph-movie", iTunesCode: "R-18", iTunesValue: "400", description: "R-18"),
        ContentRatings(country: "Pilipinas", media: "Movie & TV", prefix: "ph-movie", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated"),
        ContentRatings(country: "Hong Kong", media: "Movie & TV", prefix: "hk-movie", iTunesCode: "第i類", iTunesValue: "100", description: "第i類"),
        ContentRatings(country: "Hong Kong", media: "Movie & TV", prefix: "hk-movie", iTunesCode: "第ii類", iTunesValue: "400", description: "第ii類"),
        ContentRatings(country: "Hong Kong", media: "Movie & TV", prefix: "hk-movie", iTunesCode: "未作評級", iTunesValue: "???", description: "未作評級"),
        ContentRatings(country: "Česká Republika", media: "Movie & TV", prefix: "cz-movies", iTunesCode: "U", iTunesValue: "100", description: "U"),
        ContentRatings(country: "Česká Republika", media: "Movie & TV", prefix: "cz-movies", iTunesCode: "12+", iTunesValue: "200", description: "12+"),
        ContentRatings(country: "Česká Republika", media: "Movie & TV", prefix: "cz-movies", iTunesCode: "15+", iTunesValue: "350", description: "15+"),
        ContentRatings(country: "Česká Republika", media: "Movie & TV", prefix: "cz-movies", iTunesCode: "18+", iTunesValue: "400", description: "18+"),
        ContentRatings(country: "Česká Republika", media: "Movie & TV", prefix: "cz-movies", iTunesCode: "neklasifikováno", iTunesValue: "???", description: "neklasifikováno"),
        ContentRatings(country: "India", media: "Movie", prefix: "in-movies", iTunesCode: "U", iTunesValue: "000", description: "U"),
        ContentRatings(country: "India", media: "Movie", prefix: "in-movies", iTunesCode: "UA", iTunesValue: "200", description: "UA"),
        ContentRatings(country: "India", media: "Movie", prefix: "in-movies", iTunesCode: "A", iTunesValue: "500", description: "A"),
        ContentRatings(country: "India", media: "Movie", prefix: "in-movies", iTunesCode: "S", iTunesValue: "600", description: "S"),
        ContentRatings(country: "India", media: "Movie", prefix: "in-movies", iTunesCode: "रेट नहीं की गई", iTunesValue: "???", description: "रेट नहीं की गई"),
        ContentRatings(country: "India", media: "TV", prefix: "in-tv", iTunesCode: "U", iTunesValue: "100", description: "U"),
        ContentRatings(country: "India", media: "TV", prefix: "in-tv", iTunesCode: "UA", iTunesValue: "200", description: "UA"),
        ContentRatings(country: "India", media: "TV", prefix: "in-tv", iTunesCode: "A", iTunesValue: "600", description: "A"),
        ContentRatings(country: "India", media: "TV", prefix: "in-tv", iTunesCode: "S", iTunesValue: "600", description: "S"),
        ContentRatings(country: "All Countries", media: "Movie", prefix: "mpaa", iTunesCode: "Unrated", iTunesValue: "???", description: "Unrated")
    ]
}
