//
//  ISOLanguages.swift
//  SwiftTagger_MacOS
//
//  Created by Nolaine Crusher on 4/14/20.
//  Copyright © 2020 Nolaine Crusher. All rights reserved.
//

internal struct IsoLanguageInfo {
    
    public let isoName: String
    public let nativeName: String
    public let iso6392T: String
    public let iso6392B: String
}

internal class IsoLanguages {
    
    // swiftlint:disable line_length
    static let allLanguages: [IsoLanguageInfo] = [
        IsoLanguageInfo(isoName: "Afar",
                        nativeName: "Qafaraf; ’Afar Af; Afaraf; Qafar af",
                        iso6392T: "aar",
                        iso6392B: "aar"),
        IsoLanguageInfo(isoName: "Abkhazian",
                        nativeName: "Аҧсуа бызшәа; Аҧсшәа",
                        iso6392T: "abk",
                        iso6392B: "abk"),
        IsoLanguageInfo(isoName: "Achinese",
                        nativeName: "بهسا اچيه",
                        iso6392T: "ace",
                        iso6392B: "ace"),
        IsoLanguageInfo(isoName: "Acoli",
                        nativeName: "Lwo",
                        iso6392T: "ach",
                        iso6392B: "ach"),
        IsoLanguageInfo(isoName: "Adangme",
                        nativeName: "Dangme",
                        iso6392T: "ada",
                        iso6392B: "ada"),
        IsoLanguageInfo(isoName: "Adyghe; Adygei",
                        nativeName: "Адыгабзэ; Кӏахыбзэ",
                        iso6392T: "ady",
                        iso6392B: "ady"),
        IsoLanguageInfo(isoName: "Afro-Asiatic languages",
                        nativeName: "Afro-Asiatic languages",
                        iso6392T: "afa",
                        iso6392B: "afa"),
        IsoLanguageInfo(isoName: "Afrihili",
                        nativeName: "El-Afrihili",
                        iso6392T: "afh",
                        iso6392B: "afh"),
        IsoLanguageInfo(isoName: "Afrikaans",
                        nativeName: "Afrikaans",
                        iso6392T: "afr",
                        iso6392B: "afr"),
        IsoLanguageInfo(isoName: "Ainu",
                        nativeName: "アイヌ・イタㇰ",
                        iso6392T: "ain",
                        iso6392B: "ain"),
        IsoLanguageInfo(isoName: "Akan",
                        nativeName: "Akan",
                        iso6392T: "aka",
                        iso6392B: "aka"),
        IsoLanguageInfo(isoName: "Akkadian",
                        nativeName: "𒀝𒅗𒁺𒌑",
                        iso6392T: "akk",
                        iso6392B: "akk"),
        IsoLanguageInfo(isoName: "Albanian",
                        nativeName: "Shqip",
                        iso6392T: "sqi",
                        iso6392B: "alb"),
        IsoLanguageInfo(isoName: "Aleut",
                        nativeName: "Уна́ӈам тунуу́; Унаӈан умсуу",
                        iso6392T: "ale",
                        iso6392B: "ale"),
        IsoLanguageInfo(isoName: "Algonquian languages",
                        nativeName: "Algonquian languages",
                        iso6392T: "alg",
                        iso6392B: "alg"),
        IsoLanguageInfo(isoName: "Southern Altai",
                        nativeName: "Алтай тили",
                        iso6392T: "alt",
                        iso6392B: "alt"),
        IsoLanguageInfo(isoName: "Amharic",
                        nativeName: "አማርኛ",
                        iso6392T: "amh",
                        iso6392B: "amh"),
        IsoLanguageInfo(isoName: "English, Old (isoName: ca.450–1100)",
                        nativeName: "Ænglisc; Anglisc; Englisc",
                        iso6392T: "ang",
                        iso6392B: "ang"),
        IsoLanguageInfo(isoName: "Angika",
                        nativeName: "Angika",
                        iso6392T: "anp",
                        iso6392B: "anp"),
        IsoLanguageInfo(isoName: "Apache languages",
                        nativeName: "Apache languages",
                        iso6392T: "apa",
                        iso6392B: "apa"),
        IsoLanguageInfo(isoName: "Arabic",
                        nativeName: "العَرَبِيَّة",
                        iso6392T: "ara",
                        iso6392B: "ara"),
        IsoLanguageInfo(isoName: "Official Aramaic (isoName: 700–300 BCE); Imperial Aramaic (isoName: 700–300 BCE)",
                        nativeName: "Official Aramaic (isoName: 700–300 BCE); Imperial Aramaic (isoName: 700–300 BCE)",
                        iso6392T: "arc",
                        iso6392B: "arc"),
        IsoLanguageInfo(isoName: "Aragonese",
                        nativeName: "aragonés",
                        iso6392T: "arg",
                        iso6392B: "arg"),
        IsoLanguageInfo(isoName: "Armenian",
                        nativeName: "Հայերէն; Հայերեն",
                        iso6392T: "hye",
                        iso6392B: "arm"),
        IsoLanguageInfo(isoName: "Mapudungun; Mapuche",
                        nativeName: "Mapudungun; Mapuche",
                        iso6392T: "arn",
                        iso6392B: "arn"),
        IsoLanguageInfo(isoName: "Arapaho",
                        nativeName: "Hinónoʼeitíít",
                        iso6392T: "arp",
                        iso6392B: "arp"),
        IsoLanguageInfo(isoName: "Artificial languages",
                        nativeName: "Artificial languages",
                        iso6392T: "art",
                        iso6392B: "art"),
        IsoLanguageInfo(isoName: "Arawak",
                        nativeName: "Lokono",
                        iso6392T: "arw",
                        iso6392B: "arw"),
        IsoLanguageInfo(isoName: "Assamese",
                        nativeName: "অসমীয়া",
                        iso6392T: "asm",
                        iso6392B: "asm"),
        IsoLanguageInfo(isoName: "Asturian; Bable; Leonese; Asturleonese",
                        nativeName: "Asturianu",
                        iso6392T: "ast",
                        iso6392B: "ast"),
        IsoLanguageInfo(isoName: "Athapascan languages",
                        nativeName: "Athapascan languages",
                        iso6392T: "ath",
                        iso6392B: "ath"),
        IsoLanguageInfo(isoName: "Australian languages",
                        nativeName: "Australian languages",
                        iso6392T: "aus",
                        iso6392B: "aus"),
        IsoLanguageInfo(isoName: "Avaric",
                        nativeName: "Магӏарул мацӏ; Авар мацӏ",
                        iso6392T: "ava",
                        iso6392B: "ava"),
        IsoLanguageInfo(isoName: "Avestan",
                        nativeName: "Avestan",
                        iso6392T: "ave",
                        iso6392B: "ave"),
        IsoLanguageInfo(isoName: "Awadhi",
                        nativeName: "अवधी",
                        iso6392T: "awa",
                        iso6392B: "awa"),
        IsoLanguageInfo(isoName: "Aymara",
                        nativeName: "Aymar aru",
                        iso6392T: "aym",
                        iso6392B: "aym"),
        IsoLanguageInfo(isoName: "Azerbaijani",
                        nativeName: "Azərbaycan dili; آذربایجان دیلی; Азәрбајҹан дили",
                        iso6392T: "aze",
                        iso6392B: "aze"),
        IsoLanguageInfo(isoName: "Banda languages",
                        nativeName: "Banda languages",
                        iso6392T: "bad",
                        iso6392B: "bad"),
        IsoLanguageInfo(isoName: "Bamileke languages",
                        nativeName: "Bamiléké",
                        iso6392T: "bai",
                        iso6392B: "bai"),
        IsoLanguageInfo(isoName: "Bashkir",
                        nativeName: "Башҡорт теле; Başqort tele",
                        iso6392T: "bak",
                        iso6392B: "bak"),
        IsoLanguageInfo(isoName: "Baluchi",
                        nativeName: "بلوچی",
                        iso6392T: "bal",
                        iso6392B: "bal"),
        IsoLanguageInfo(isoName: "Bambara",
                        nativeName: "ߓߊߡߊߣߊߣߞߊߣ",
                        iso6392T: "bam",
                        iso6392B: "bam"),
        IsoLanguageInfo(isoName: "Balinese",
                        nativeName: "ᬪᬵᬱᬩᬮᬶ; ᬩᬲᬩᬮᬶ",
                        iso6392T: "ban",
                        iso6392B: "ban"),
        IsoLanguageInfo(isoName: "Basque",
                        nativeName: "euskara",
                        iso6392T: "eus",
                        iso6392B: "baq"),
        IsoLanguageInfo(isoName: "Basa",
                        nativeName: "Mbene; Ɓasaá",
                        iso6392T: "bas",
                        iso6392B: "bas"),
        IsoLanguageInfo(isoName: "Baltic languages",
                        nativeName: "Baltic languages",
                        iso6392T: "bat",
                        iso6392B: "bat"),
        IsoLanguageInfo(isoName: "Beja; Bedawiyet",
                        nativeName: "Bidhaawyeet",
                        iso6392T: "bej",
                        iso6392B: "bej"),
        IsoLanguageInfo(isoName: "Belarusian",
                        nativeName: "Беларуская мова",
                        iso6392T: "bel",
                        iso6392B: "bel"),
        IsoLanguageInfo(isoName: "Bemba",
                        nativeName: "Chibemba",
                        iso6392T: "bem",
                        iso6392B: "bem"),
        IsoLanguageInfo(isoName: "Bengali",
                        nativeName: "বাংলা",
                        iso6392T: "ben",
                        iso6392B: "ben"),
        IsoLanguageInfo(isoName: "Berber languages",
                        nativeName: "Tamaziɣt; Tamazight; ⵜⴰⵎⴰⵣⵉⵖⵜ; ⵝⴰⵎⴰⵣⵉⵗⵝ; ⵜⴰⵎⴰⵣⵉⵗⵜ",
                        iso6392T: "ber",
                        iso6392B: "ber"),
        IsoLanguageInfo(isoName: "Bhojpuri",
                        nativeName: "भोजपुरी",
                        iso6392T: "bho",
                        iso6392B: "bho"),
        IsoLanguageInfo(isoName: "Bihari languages",
                        nativeName: "Bihari languages",
                        iso6392T: "bih",
                        iso6392B: "bih"),
        IsoLanguageInfo(isoName: "Bikol",
                        nativeName: "Bikol",
                        iso6392T: "bik",
                        iso6392B: "bik"),
        IsoLanguageInfo(isoName: "Bini; Edo",
                        nativeName: "Ẹ̀dó",
                        iso6392T: "bin",
                        iso6392B: "bin"),
        IsoLanguageInfo(isoName: "Bislama",
                        nativeName: "Bislama",
                        iso6392T: "bis",
                        iso6392B: "bis"),
        IsoLanguageInfo(isoName: "Siksika",
                        nativeName: "ᓱᖽᐧᖿ",
                        iso6392T: "bla",
                        iso6392B: "bla"),
        IsoLanguageInfo(isoName: "Bantu (isoName: Other)",
                        nativeName: "Bantu (isoName: Other)",
                        iso6392T: "bnt",
                        iso6392B: "bnt"),
        IsoLanguageInfo(isoName: "Tibetan",
                        nativeName: "བོད་སྐད་; ལྷ་སའི་སྐད་",
                        iso6392T: "bod",
                        iso6392B: "tib"),
        IsoLanguageInfo(isoName: "Bosnian",
                        nativeName: "bosanski; босански",
                        iso6392T: "bos",
                        iso6392B: "bos"),
        IsoLanguageInfo(isoName: "Braj",
                        nativeName: "Braj",
                        iso6392T: "bra",
                        iso6392B: "bra"),
        IsoLanguageInfo(isoName: "Breton",
                        nativeName: "Brezhoneg",
                        iso6392T: "bre",
                        iso6392B: "bre"),
        IsoLanguageInfo(isoName: "Batak languages",
                        nativeName: "Batak languages",
                        iso6392T: "btk",
                        iso6392B: "btk"),
        IsoLanguageInfo(isoName: "Buriat",
                        nativeName: "буряад хэлэн",
                        iso6392T: "bua",
                        iso6392B: "bua"),
        IsoLanguageInfo(isoName: "Buginese",
                        nativeName: "ᨅᨔ ᨕᨘᨁᨗ",
                        iso6392T: "bug",
                        iso6392B: "bug"),
        IsoLanguageInfo(isoName: "Bulgarian",
                        nativeName: "български език",
                        iso6392T: "bul",
                        iso6392B: "bul"),
        IsoLanguageInfo(isoName: "Burmese",
                        nativeName: "မြန်မာစာ; မြန်မာစကား",
                        iso6392T: "mya",
                        iso6392B: "bur"),
        IsoLanguageInfo(isoName: "Blin; Bilin",
                        nativeName: "ብሊና; ብሊን",
                        iso6392T: "byn",
                        iso6392B: "byn"),
        IsoLanguageInfo(isoName: "Caddo",
                        nativeName: "Hasí:nay",
                        iso6392T: "cad",
                        iso6392B: "cad"),
        IsoLanguageInfo(isoName: "Central American Indian languages",
                        nativeName: "Central American Indian languages",
                        iso6392T: "cai",
                        iso6392B: "cai"),
        IsoLanguageInfo(isoName: "Galibi Carib",
                        nativeName: "Kari'nja",
                        iso6392T: "car",
                        iso6392B: "car"),
        IsoLanguageInfo(isoName: "Catalan; Valencian",
                        nativeName: "català",
                        iso6392T: "cat",
                        iso6392B: "cat"),
        IsoLanguageInfo(isoName: "Caucasian languages",
                        nativeName: "Caucasian languages",
                        iso6392T: "cau",
                        iso6392B: "cau"),
        IsoLanguageInfo(isoName: "Cebuano",
                        nativeName: "Sinugbuanong Binisayâ",
                        iso6392T: "ceb",
                        iso6392B: "ceb"),
        IsoLanguageInfo(isoName: "Celtic languages",
                        nativeName: "Celtic languages",
                        iso6392T: "cel",
                        iso6392B: "cel"),
        IsoLanguageInfo(isoName: "Czech",
                        nativeName: "čeština; český jazyk",
                        iso6392T: "ces",
                        iso6392B: "cze"),
        IsoLanguageInfo(isoName: "Chamorro",
                        nativeName: "Finu' Chamoru",
                        iso6392T: "cha",
                        iso6392B: "cha"),
        IsoLanguageInfo(isoName: "Chibcha",
                        nativeName: "Muysccubun",
                        iso6392T: "chb",
                        iso6392B: "chb"),
        IsoLanguageInfo(isoName: "Chechen",
                        nativeName: "Нохчийн мотт; نَاخچیین موٓتت; ნახჩიე მუოთთ",
                        iso6392T: "che",
                        iso6392B: "che"),
        IsoLanguageInfo(isoName: "Chagatai",
                        nativeName: "جغتای",
                        iso6392T: "chg",
                        iso6392B: "chg"),
        IsoLanguageInfo(isoName: "Chinese",
                        nativeName: "中文; 汉语; 漢語",
                        iso6392T: "zho",
                        iso6392B: "chi"),
        IsoLanguageInfo(isoName: "Chuukese",
                        nativeName: "Chuukese",
                        iso6392T: "chk",
                        iso6392B: "chk"),
        IsoLanguageInfo(isoName: "Mari",
                        nativeName: "марий йылме",
                        iso6392T: "chm",
                        iso6392B: "chm"),
        IsoLanguageInfo(isoName: "Chinook jargon",
                        nativeName: "chinuk wawa; wawa; chinook lelang; lelang",
                        iso6392T: "chn",
                        iso6392B: "chn"),
        IsoLanguageInfo(isoName: "Choctaw",
                        nativeName: "Chahta'",
                        iso6392T: "cho",
                        iso6392B: "cho"),
        IsoLanguageInfo(isoName: "Chipewyan; Dene Suline",
                        nativeName: "ᑌᓀᓱᒼᕄᓀ (isoName: Dënesųłiné)",
                        iso6392T: "chp",
                        iso6392B: "chp"),
        IsoLanguageInfo(isoName: "Cherokee",
                        nativeName: "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ",
                        iso6392T: "chr",
                        iso6392B: "chr"),
        IsoLanguageInfo(isoName: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
                        nativeName: "Славе́нскїй ѧ҆зы́къ",
                        iso6392T: "chu",
                        iso6392B: "chu"),
        IsoLanguageInfo(isoName: "Chuvash",
                        nativeName: "Чӑвашла",
                        iso6392T: "chv",
                        iso6392B: "chv"),
        IsoLanguageInfo(isoName: "Cheyenne",
                        nativeName: "Tsėhésenėstsestȯtse",
                        iso6392T: "chy",
                        iso6392B: "chy"),
        IsoLanguageInfo(isoName: "Chamic languages",
                        nativeName: "Chamic languages",
                        iso6392T: "cmc",
                        iso6392B: "cmc"),
        IsoLanguageInfo(isoName: "Montenegrin",
                        nativeName: "crnogorski / црногорски",
                        iso6392T: "cnr",
                        iso6392B: "cnr"),
        IsoLanguageInfo(isoName: "Coptic",
                        nativeName: "ϯⲙⲉⲑⲣⲉⲙⲛ̀ⲭⲏⲙⲓ; ⲧⲙⲛ̄ⲧⲣⲙ̄ⲛ̄ⲕⲏⲙⲉ",
                        iso6392T: "cop",
                        iso6392B: "cop"),
        IsoLanguageInfo(isoName: "Cornish",
                        nativeName: "Kernowek",
                        iso6392T: "cor",
                        iso6392B: "cor"),
        IsoLanguageInfo(isoName: "Corsican",
                        nativeName: "Corsu; Lingua corsa",
                        iso6392T: "cos",
                        iso6392B: "cos"),
        IsoLanguageInfo(isoName: "Creoles and pidgins, English based",
                        nativeName: "Creoles and pidgins, English based",
                        iso6392T: "cpe",
                        iso6392B: "cpe"),
        IsoLanguageInfo(isoName: "Creoles and pidgins, French-based",
                        nativeName: "Creoles and pidgins, French-based",
                        iso6392T: "cpf",
                        iso6392B: "cpf"),
        IsoLanguageInfo(isoName: "Creoles and pidgins, Portuguese-based",
                        nativeName: "Creoles and pidgins, Portuguese-based",
                        iso6392T: "cpp",
                        iso6392B: "cpp"),
        IsoLanguageInfo(isoName: "Cree",
                        nativeName: "Cree",
                        iso6392T: "cre",
                        iso6392B: "cre"),
        IsoLanguageInfo(isoName: "Crimean Tatar; Crimean Turkish",
                        nativeName: "Къырымтатарджа; Къырымтатар тили; Ҡырымтатарҗа; Ҡырымтатар тили",
                        iso6392T: "crh",
                        iso6392B: "crh"),
        IsoLanguageInfo(isoName: "Creoles and pidgins",
                        nativeName: "Creoles and pidgins",
                        iso6392T: "crp",
                        iso6392B: "crp"),
        IsoLanguageInfo(isoName: "Kashubian",
                        nativeName: "Kaszëbsczi jãzëk",
                        iso6392T: "csb",
                        iso6392B: "csb"),
        IsoLanguageInfo(isoName: "Cushitic languages",
                        nativeName: "Cushitic languages",
                        iso6392T: "cus",
                        iso6392B: "cus"),
        IsoLanguageInfo(isoName: "Welsh",
                        nativeName: "Cymraeg; y Gymraeg",
                        iso6392T: "cym",
                        iso6392B: "wel"),
        IsoLanguageInfo(isoName: "Dakota",
                        nativeName: "Dakhótiyapi; Dakȟótiyapi",
                        iso6392T: "dak",
                        iso6392B: "dak"),
        IsoLanguageInfo(isoName: "Danish",
                        nativeName: "dansk",
                        iso6392T: "dan",
                        iso6392B: "dan"),
        IsoLanguageInfo(isoName: "Dargwa",
                        nativeName: "дарган мез",
                        iso6392T: "dar",
                        iso6392B: "dar"),
        IsoLanguageInfo(isoName: "Land Dayak languages",
                        nativeName: "Land Dayak languages",
                        iso6392T: "day",
                        iso6392B: "day"),
        IsoLanguageInfo(isoName: "Delaware",
                        nativeName: "Delaware",
                        iso6392T: "del",
                        iso6392B: "del"),
        IsoLanguageInfo(isoName: "Slave (isoName: Athapascan)",
                        nativeName: "Dene K'e",
                        iso6392T: "den",
                        iso6392B: "den"),
        IsoLanguageInfo(isoName: "German",
                        nativeName: "Deutsch",
                        iso6392T: "deu",
                        iso6392B: "ger"),
        IsoLanguageInfo(isoName: "Dogrib",
                        nativeName: "डोगरी; ڈوگرى",
                        iso6392T: "dgr",
                        iso6392B: "dgr"),
        IsoLanguageInfo(isoName: "Dinka",
                        nativeName: "Thuɔŋjäŋ",
                        iso6392T: "din",
                        iso6392B: "din"),
        IsoLanguageInfo(isoName: "Divehi; Dhivehi; Maldivian",
                        nativeName: "ދިވެހި; ދިވެހިބަސް",
                        iso6392T: "div",
                        iso6392B: "div"),
        IsoLanguageInfo(isoName: "Dogri",
                        nativeName: "डोगरी; ڈوگرى",
                        iso6392T: "doi",
                        iso6392B: "doi"),
        IsoLanguageInfo(isoName: "Dravidian languages",
                        nativeName: "Dravidian languages",
                        iso6392T: "dra",
                        iso6392B: "dra"),
        IsoLanguageInfo(isoName: "Lower Sorbian",
                        nativeName: "Dolnoserbski; Dolnoserbšćina",
                        iso6392T: "dsb",
                        iso6392B: "dsb"),
        IsoLanguageInfo(isoName: "Duala",
                        nativeName: "Duala",
                        iso6392T: "dua",
                        iso6392B: "dua"),
        IsoLanguageInfo(isoName: "Dutch, Middle (isoName: ca. 1050–1350)",
                        nativeName: "Dutch, Middle (isoName: ca. 1050–1350)",
                        iso6392T: "dum",
                        iso6392B: "dum"),
        IsoLanguageInfo(isoName: "Dutch; Flemish",
                        nativeName: "Nederlands; Vlaams",
                        iso6392T: "nld",
                        iso6392B: "dut"),
        IsoLanguageInfo(isoName: "Dyula",
                        nativeName: "Julakan",
                        iso6392T: "dyu",
                        iso6392B: "dyu"),
        IsoLanguageInfo(isoName: "Dzongkha",
                        nativeName: "རྫོང་ཁ་",
                        iso6392T: "dzo",
                        iso6392B: "dzo"),
        IsoLanguageInfo(isoName: "Efik",
                        nativeName: "Efik",
                        iso6392T: "efi",
                        iso6392B: "efi"),
        IsoLanguageInfo(isoName: "Egyptian (isoName: Ancient)",
                        nativeName: "Egyptian (isoName: Ancient)",
                        iso6392T: "egy",
                        iso6392B: "egy"),
        IsoLanguageInfo(isoName: "Ekajuk",
                        nativeName: "Ekajuk",
                        iso6392T: "eka",
                        iso6392B: "eka"),
        IsoLanguageInfo(isoName: "Greek, Modern (isoName: 1453–)",
                        nativeName: "Νέα Ελληνικά",
                        iso6392T: "ell",
                        iso6392B: "gre"),
        IsoLanguageInfo(isoName: "Elamite",
                        nativeName: "Elamite",
                        iso6392T: "elx",
                        iso6392B: "elx"),
        IsoLanguageInfo(isoName: "English",
                        nativeName: "English",
                        iso6392T: "eng",
                        iso6392B: "eng"),
        IsoLanguageInfo(isoName: "English, Middle (isoName: 1100–1500)",
                        nativeName: "English, Middle (isoName: 1100–1500)",
                        iso6392T: "enm",
                        iso6392B: "enm"),
        IsoLanguageInfo(isoName: "Esperanto",
                        nativeName: "Esperanto",
                        iso6392T: "epo",
                        iso6392B: "epo"),
        IsoLanguageInfo(isoName: "Estonian",
                        nativeName: "eesti keel",
                        iso6392T: "est",
                        iso6392B: "est"),
        IsoLanguageInfo(isoName: "Ewe",
                        nativeName: "Èʋegbe",
                        iso6392T: "ewe",
                        iso6392B: "ewe"),
        IsoLanguageInfo(isoName: "Ewondo",
                        nativeName: "Ewondo",
                        iso6392T: "ewo",
                        iso6392B: "ewo"),
        IsoLanguageInfo(isoName: "Fang",
                        nativeName: "Fang",
                        iso6392T: "fan",
                        iso6392B: "fan"),
        IsoLanguageInfo(isoName: "Faroese",
                        nativeName: "føroyskt",
                        iso6392T: "fao",
                        iso6392B: "fao"),
        IsoLanguageInfo(isoName: "Persian",
                        nativeName: "فارسی",
                        iso6392T: "fas",
                        iso6392B: "per"),
        IsoLanguageInfo(isoName: "Fanti",
                        nativeName: "Mfantse; Fante; Fanti",
                        iso6392T: "fat",
                        iso6392B: "fat"),
        IsoLanguageInfo(isoName: "Fijian",
                        nativeName: "Na Vosa Vakaviti",
                        iso6392T: "fij",
                        iso6392B: "fij"),
        IsoLanguageInfo(isoName: "Filipino; Pilipino",
                        nativeName: "Wikang Filipino",
                        iso6392T: "fil",
                        iso6392B: "fil"),
        IsoLanguageInfo(isoName: "Finnish",
                        nativeName: "suomen kieli",
                        iso6392T: "fin",
                        iso6392B: "fin"),
        IsoLanguageInfo(isoName: "Finno-Ugrian languages",
                        nativeName: "Finno-Ugrian languages",
                        iso6392T: "fiu",
                        iso6392B: "fiu"),
        IsoLanguageInfo(isoName: "Fon",
                        nativeName: "Fon gbè",
                        iso6392T: "fon",
                        iso6392B: "fon"),
        IsoLanguageInfo(isoName: "French",
                        nativeName: "français",
                        iso6392T: "fra",
                        iso6392B: "fre"),
        IsoLanguageInfo(isoName: "French, Middle (isoName: ca. 1400–1600)",
                        nativeName: "françois; franceis",
                        iso6392T: "frm",
                        iso6392B: "frm"),
        IsoLanguageInfo(isoName: "French, Old (isoName: 842–ca. 1400)",
                        nativeName: "Franceis; François; Romanz",
                        iso6392T: "fro",
                        iso6392B: "fro"),
        IsoLanguageInfo(isoName: "Northern Frisian",
                        nativeName: "Frasch; Fresk; Freesk; Friisk",
                        iso6392T: "frr",
                        iso6392B: "frr"),
        IsoLanguageInfo(isoName: "Eastern Frisian",
                        nativeName: "Seeltersk",
                        iso6392T: "frs",
                        iso6392B: "frs"),
        IsoLanguageInfo(isoName: "Western Frisian",
                        nativeName: "Frysk",
                        iso6392T: "fry",
                        iso6392B: "fry"),
        IsoLanguageInfo(isoName: "Fulah",
                        nativeName: "Fulfulde; Pulaar; Pular",
                        iso6392T: "ful",
                        iso6392B: "ful"),
        IsoLanguageInfo(isoName: "Friulian",
                        nativeName: "Furlan",
                        iso6392T: "fur",
                        iso6392B: "fur"),
        IsoLanguageInfo(isoName: "Ga",
                        nativeName: "Gã",
                        iso6392T: "gaa",
                        iso6392B: "gaa"),
        IsoLanguageInfo(isoName: "Gayo",
                        nativeName: "Basa Gayo",
                        iso6392T: "gay",
                        iso6392B: "gay"),
        IsoLanguageInfo(isoName: "Gbaya",
                        nativeName: "Gbaya",
                        iso6392T: "gba",
                        iso6392B: "gba"),
        IsoLanguageInfo(isoName: "Germanic languages",
                        nativeName: "Germanic languages",
                        iso6392T: "gem",
                        iso6392B: "gem"),
        IsoLanguageInfo(isoName: "Georgian",
                        nativeName: "ქართული",
                        iso6392T: "kat",
                        iso6392B: "geo"),
        IsoLanguageInfo(isoName: "Geez",
                        nativeName: "ግዕዝ",
                        iso6392T: "gez",
                        iso6392B: "gez"),
        IsoLanguageInfo(isoName: "Gilbertese",
                        nativeName: "Taetae ni Kiribati",
                        iso6392T: "gil",
                        iso6392B: "gil"),
        IsoLanguageInfo(isoName: "Gaelic; Scottish Gaelic",
                        nativeName: "Gàidhlig",
                        iso6392T: "gla",
                        iso6392B: "gla"),
        IsoLanguageInfo(isoName: "Irish",
                        nativeName: "Gaeilge",
                        iso6392T: "gle",
                        iso6392B: "gle"),
        IsoLanguageInfo(isoName: "Galician",
                        nativeName: "galego",
                        iso6392T: "glg",
                        iso6392B: "glg"),
        IsoLanguageInfo(isoName: "Manx",
                        nativeName: "Gaelg; Gailck",
                        iso6392T: "glv",
                        iso6392B: "glv"),
        IsoLanguageInfo(isoName: "German, Middle High (isoName: ca. 1050–1500)",
                        nativeName: "Diutsch",
                        iso6392T: "gmh",
                        iso6392B: "gmh"),
        IsoLanguageInfo(isoName: "German, Old High (isoName: ca. 750–1050)",
                        nativeName: "Diutisk",
                        iso6392T: "goh",
                        iso6392B: "goh"),
        IsoLanguageInfo(isoName: "Gondi",
                        nativeName: "Gondi",
                        iso6392T: "gon",
                        iso6392B: "gon"),
        IsoLanguageInfo(isoName: "Gorontalo",
                        nativeName: "Bahasa Hulontalo",
                        iso6392T: "gor",
                        iso6392B: "gor"),
        IsoLanguageInfo(isoName: "Gothic",
                        nativeName: "Gothic",
                        iso6392T: "got",
                        iso6392B: "got"),
        IsoLanguageInfo(isoName: "Grebo",
                        nativeName: "Grebo",
                        iso6392T: "grb",
                        iso6392B: "grb"),
        IsoLanguageInfo(isoName: "Greek, Ancient (isoName: to 1453)",
                        nativeName: "Ἑλληνική",
                        iso6392T: "grc",
                        iso6392B: "grc"),
        IsoLanguageInfo(isoName: "Guarani",
                        nativeName: "Avañe'ẽ",
                        iso6392T: "grn",
                        iso6392B: "grn"),
        IsoLanguageInfo(isoName: "Swiss German; Alemannic; Alsatian",
                        nativeName: "Schwiizerdütsch",
                        iso6392T: "gsw",
                        iso6392B: "gsw"),
        IsoLanguageInfo(isoName: "Gujarati",
                        nativeName: "ગુજરાતી",
                        iso6392T: "guj",
                        iso6392B: "guj"),
        IsoLanguageInfo(isoName: "Gwich'in",
                        nativeName: "Dinjii Zhu’ Ginjik",
                        iso6392T: "gwi",
                        iso6392B: "gwi"),
        IsoLanguageInfo(isoName: "Haida",
                        nativeName: "X̱aat Kíl; X̱aadas Kíl; X̱aayda Kil; Xaad kil",
                        iso6392T: "hai",
                        iso6392B: "hai"),
        IsoLanguageInfo(isoName: "Haitian; Haitian Creole",
                        nativeName: "kreyòl ayisyen",
                        iso6392T: "hat",
                        iso6392B: "hat"),
        IsoLanguageInfo(isoName: "Hausa",
                        nativeName: "Harshen Hausa; هَرْشَن",
                        iso6392T: "hau",
                        iso6392B: "hau"),
        IsoLanguageInfo(isoName: "Hawaiian",
                        nativeName: "ʻŌlelo Hawaiʻi",
                        iso6392T: "haw",
                        iso6392B: "haw"),
        IsoLanguageInfo(isoName: "Hebrew",
                        nativeName: "עברית",
                        iso6392T: "heb",
                        iso6392B: "heb"),
        IsoLanguageInfo(isoName: "Herero",
                        nativeName: "Otjiherero",
                        iso6392T: "her",
                        iso6392B: "her"),
        IsoLanguageInfo(isoName: "Hiligaynon",
                        nativeName: "Ilonggo",
                        iso6392T: "hil",
                        iso6392B: "hil"),
        IsoLanguageInfo(isoName: "Himachali languages; Pahari languages",
                        nativeName: "Himachali languages; Pahari languages",
                        iso6392T: "him",
                        iso6392B: "him"),
        IsoLanguageInfo(isoName: "Hindi",
                        nativeName: "हिन्दी",
                        iso6392T: "hin",
                        iso6392B: "hin"),
        IsoLanguageInfo(isoName: "Hittite",
                        nativeName: "𒉈𒅆𒇷",
                        iso6392T: "hit",
                        iso6392B: "hit"),
        IsoLanguageInfo(isoName: "Hmong; Mong",
                        nativeName: "lus Hmoob; lug Moob; lol Hmongb",
                        iso6392T: "hmn",
                        iso6392B: "hmn"),
        IsoLanguageInfo(isoName: "Hiri Motu",
                        nativeName: "Hiri Motu",
                        iso6392T: "hmo",
                        iso6392B: "hmo"),
        IsoLanguageInfo(isoName: "Croatian",
                        nativeName: "hrvatski",
                        iso6392T: "hrv",
                        iso6392B: "hrv"),
        IsoLanguageInfo(isoName: "Upper Sorbian",
                        nativeName: "hornjoserbšćina",
                        iso6392T: "hsb",
                        iso6392B: "hsb"),
        IsoLanguageInfo(isoName: "Hungarian",
                        nativeName: "magyar nyelv",
                        iso6392T: "hun",
                        iso6392B: "hun"),
        IsoLanguageInfo(isoName: "Hupa",
                        nativeName: "Na:tinixwe Mixine:whe'",
                        iso6392T: "hup",
                        iso6392B: "hup"),
        IsoLanguageInfo(isoName: "Iban",
                        nativeName: "Jaku Iban",
                        iso6392T: "iba",
                        iso6392B: "iba"),
        IsoLanguageInfo(isoName: "Igbo",
                        nativeName: "Asụsụ Igbo",
                        iso6392T: "ibo",
                        iso6392B: "ibo"),
        IsoLanguageInfo(isoName: "Icelandic",
                        nativeName: "íslenska",
                        iso6392T: "isl",
                        iso6392B: "ice"),
        IsoLanguageInfo(isoName: "Ido",
                        nativeName: "Ido",
                        iso6392T: "ido",
                        iso6392B: "ido"),
        IsoLanguageInfo(isoName: "Sichuan Yi; Nuosu",
                        nativeName: "ꆈꌠꉙ",
                        iso6392T: "iii",
                        iso6392B: "iii"),
        IsoLanguageInfo(isoName: "Ijo languages",
                        nativeName: "Ịjọ",
                        iso6392T: "ijo",
                        iso6392B: "ijo"),
        IsoLanguageInfo(isoName: "Inuktitut",
                        nativeName: "ᐃᓄᒃᑎᑐᑦ",
                        iso6392T: "iku",
                        iso6392B: "iku"),
        IsoLanguageInfo(isoName: "Interlingue; Occidental",
                        nativeName: "Interlingue; Occidental",
                        iso6392T: "ile",
                        iso6392B: "ile"),
        IsoLanguageInfo(isoName: "Iloko",
                        nativeName: "Pagsasao nga Ilokano; Ilokano",
                        iso6392T: "ilo",
                        iso6392B: "ilo"),
        IsoLanguageInfo(isoName: "Interlingua (isoName: International Auxiliary Language Association)",
                        nativeName: "Interlingua (isoName: International Auxiliary Language Association)",
                        iso6392T: "ina",
                        iso6392B: "ina"),
        IsoLanguageInfo(isoName: "Indic languages",
                        nativeName: "Indic languages",
                        iso6392T: "inc",
                        iso6392B: "inc"),
        IsoLanguageInfo(isoName: "Indonesian",
                        nativeName: "bahasa Indonesia",
                        iso6392T: "ind",
                        iso6392B: "ind"),
        IsoLanguageInfo(isoName: "Indo-European languages",
                        nativeName: "Indo-European languages",
                        iso6392T: "ine",
                        iso6392B: "ine"),
        IsoLanguageInfo(isoName: "Ingush",
                        nativeName: "ГӀалгӀай мотт",
                        iso6392T: "inh",
                        iso6392B: "inh"),
        IsoLanguageInfo(isoName: "Inupiaq",
                        nativeName: "Iñupiaq",
                        iso6392T: "ipk",
                        iso6392B: "ipk"),
        IsoLanguageInfo(isoName: "Iranian languages",
                        nativeName: "Iranian languages",
                        iso6392T: "ira",
                        iso6392B: "ira"),
        IsoLanguageInfo(isoName: "Iroquoian languages",
                        nativeName: "Iroquoian languages",
                        iso6392T: "iro",
                        iso6392B: "iro"),
        IsoLanguageInfo(isoName: "Italian",
                        nativeName: "italiano; lingua italiana",
                        iso6392T: "ita",
                        iso6392B: "ita"),
        IsoLanguageInfo(isoName: "Javanese",
                        nativeName: "ꦧꦱꦗꦮ",
                        iso6392T: "jav",
                        iso6392B: "jav"),
        IsoLanguageInfo(isoName: "Lojban",
                        nativeName: "la .lojban.",
                        iso6392T: "jbo",
                        iso6392B: "jbo"),
        IsoLanguageInfo(isoName: "Japanese",
                        nativeName: "日本語",
                        iso6392T: "jpn",
                        iso6392B: "jpn"),
        IsoLanguageInfo(isoName: "Judeo-Persian",
                        nativeName: "Dzhidi",
                        iso6392T: "jpr",
                        iso6392B: "jpr"),
        IsoLanguageInfo(isoName: "Judeo-Arabic",
                        nativeName: "عربية يهودية / ערבית יהודית",
                        iso6392T: "jrb",
                        iso6392B: "jrb"),
        IsoLanguageInfo(isoName: "Kara-Kalpak",
                        nativeName: "Qaraqalpaq tili; Қарақалпақ тили",
                        iso6392T: "kaa",
                        iso6392B: "kaa"),
        IsoLanguageInfo(isoName: "Kabyle",
                        nativeName: "Tamaziɣt Taqbaylit; Tazwawt",
                        iso6392T: "kab",
                        iso6392B: "kab"),
        IsoLanguageInfo(isoName: "Kachin; Jingpho",
                        nativeName: "Jingpho",
                        iso6392T: "kac",
                        iso6392B: "kac"),
        IsoLanguageInfo(isoName: "Kalaallisut; Greenlandic",
                        nativeName: "Kalaallisut; Greenlandic",
                        iso6392T: "kal",
                        iso6392B: "kal"),
        IsoLanguageInfo(isoName: "Kamba",
                        nativeName: "Kamba",
                        iso6392T: "kam",
                        iso6392B: "kam"),
        IsoLanguageInfo(isoName: "Kannada",
                        nativeName: "ಕನ್ನಡ",
                        iso6392T: "kan",
                        iso6392B: "kan"),
        IsoLanguageInfo(isoName: "Karen languages",
                        nativeName: "Karen languages",
                        iso6392T: "kar",
                        iso6392B: "kar"),
        IsoLanguageInfo(isoName: "Kashmiri",
                        nativeName: "कॉशुर / كأشُر",
                        iso6392T: "kas",
                        iso6392B: "kas"),
        IsoLanguageInfo(isoName: "Kanuri",
                        nativeName: "Kanuri",
                        iso6392T: "kau",
                        iso6392B: "kau"),
        IsoLanguageInfo(isoName: "Kawi",
                        nativeName: "ꦧꦱꦗꦮ",
                        iso6392T: "kaw",
                        iso6392B: "kaw"),
        IsoLanguageInfo(isoName: "Kazakh",
                        nativeName: "қазақ тілі / qazaq tili",
                        iso6392T: "kaz",
                        iso6392B: "kaz"),
        IsoLanguageInfo(isoName: "Kabardian",
                        nativeName: "Адыгэбзэ (isoName: Къэбэрдейбзэ)",
                        iso6392T: "kbd",
                        iso6392B: "kbd"),
        IsoLanguageInfo(isoName: "Khasi",
                        nativeName: "কা কতিয়েন খাশি",
                        iso6392T: "kha",
                        iso6392B: "kha"),
        IsoLanguageInfo(isoName: "Khoisan languages",
                        nativeName: "Khoisan languages",
                        iso6392T: "khi",
                        iso6392B: "khi"),
        IsoLanguageInfo(isoName: "Central Khmer",
                        nativeName: "ភាសាខ្មែរ",
                        iso6392T: "khm",
                        iso6392B: "khm"),
        IsoLanguageInfo(isoName: "Khotanese; Sakan",
                        nativeName: "Khotanese; Sakan",
                        iso6392T: "kho",
                        iso6392B: "kho"),
        IsoLanguageInfo(isoName: "Kikuyu; Gikuyu",
                        nativeName: "Gĩkũyũ",
                        iso6392T: "kik",
                        iso6392B: "kik"),
        IsoLanguageInfo(isoName: "Kinyarwanda",
                        nativeName: "Kinyarwanda",
                        iso6392T: "kin",
                        iso6392B: "kin"),
        IsoLanguageInfo(isoName: "Kirghiz; Kyrgyz",
                        nativeName: "кыргызча; кыргыз тили",
                        iso6392T: "kir",
                        iso6392B: "kir"),
        IsoLanguageInfo(isoName: "Kimbundu",
                        nativeName: "Kimbundu",
                        iso6392T: "kmb",
                        iso6392B: "kmb"),
        IsoLanguageInfo(isoName: "Konkani",
                        nativeName: "कोंकणी",
                        iso6392T: "kok",
                        iso6392B: "kok"),
        IsoLanguageInfo(isoName: "Komi",
                        nativeName: "Коми кыв",
                        iso6392T: "kom",
                        iso6392B: "kom"),
        IsoLanguageInfo(isoName: "Kongo",
                        nativeName: "Kongo",
                        iso6392T: "kon",
                        iso6392B: "kon"),
        IsoLanguageInfo(isoName: "Korean",
                        nativeName: "한국어",
                        iso6392T: "kor",
                        iso6392B: "kor"),
        IsoLanguageInfo(isoName: "Kosraean",
                        nativeName: "Kosraean",
                        iso6392T: "kos",
                        iso6392B: "kos"),
        IsoLanguageInfo(isoName: "Kpelle",
                        nativeName: "Kpɛlɛwoo",
                        iso6392T: "kpe",
                        iso6392B: "kpe"),
        IsoLanguageInfo(isoName: "Karachay-Balkar",
                        nativeName: "Къарачай-Малкъар тил; Таулу тил",
                        iso6392T: "krc",
                        iso6392B: "krc"),
        IsoLanguageInfo(isoName: "Karelian",
                        nativeName: "karjal; kariela; karjala",
                        iso6392T: "krl",
                        iso6392B: "krl"),
        IsoLanguageInfo(isoName: "Kru languages",
                        nativeName: "Kru languages",
                        iso6392T: "kro",
                        iso6392B: "kro"),
        IsoLanguageInfo(isoName: "Kurukh",
                        nativeName: "कुड़ुख़",
                        iso6392T: "kru",
                        iso6392B: "kru"),
        IsoLanguageInfo(isoName: "Kuanyama; Kwanyama",
                        nativeName: "Kuanyama; Kwanyama",
                        iso6392T: "kua",
                        iso6392B: "kua"),
        IsoLanguageInfo(isoName: "Kumyk",
                        nativeName: "къумукъ тил/qumuq til",
                        iso6392T: "kum",
                        iso6392B: "kum"),
        IsoLanguageInfo(isoName: "Kurdish",
                        nativeName: "Kurdî / کوردی",
                        iso6392T: "kur",
                        iso6392B: "kur"),
        IsoLanguageInfo(isoName: "Kutenai",
                        nativeName: "Kutenai",
                        iso6392T: "kut",
                        iso6392B: "kut"),
        IsoLanguageInfo(isoName: "Ladino",
                        nativeName: "Judeo-español",
                        iso6392T: "lad",
                        iso6392B: "lad"),
        IsoLanguageInfo(isoName: "Lahnda",
                        nativeName: "بھارت کا",
                        iso6392T: "lah",
                        iso6392B: "lah"),
        IsoLanguageInfo(isoName: "Lamba",
                        nativeName: "Lamba",
                        iso6392T: "lam",
                        iso6392B: "lam"),
        IsoLanguageInfo(isoName: "Lao",
                        nativeName: "ພາສາລາວ",
                        iso6392T: "lao",
                        iso6392B: "lao"),
        IsoLanguageInfo(isoName: "Latin",
                        nativeName: "Lingua latīna",
                        iso6392T: "lat",
                        iso6392B: "lat"),
        IsoLanguageInfo(isoName: "Latvian",
                        nativeName: "Latviešu valoda",
                        iso6392T: "lav",
                        iso6392B: "lav"),
        IsoLanguageInfo(isoName: "Lezghian",
                        nativeName: "Лезги чӏал",
                        iso6392T: "lez",
                        iso6392B: "lez"),
        IsoLanguageInfo(isoName: "Limburgan; Limburger; Limburgish",
                        nativeName: "Lèmburgs",
                        iso6392T: "lim",
                        iso6392B: "lim"),
        IsoLanguageInfo(isoName: "Lingala",
                        nativeName: "Lingala",
                        iso6392T: "lin",
                        iso6392B: "lin"),
        IsoLanguageInfo(isoName: "Lithuanian",
                        nativeName: "lietuvių kalba",
                        iso6392T: "lit",
                        iso6392B: "lit"),
        IsoLanguageInfo(isoName: "Mongo",
                        nativeName: "Lomongo",
                        iso6392T: "lol",
                        iso6392B: "lol"),
        IsoLanguageInfo(isoName: "Lozi",
                        nativeName: "Lozi",
                        iso6392T: "loz",
                        iso6392B: "loz"),
        IsoLanguageInfo(isoName: "Luxembourgish; Letzeburgesch",
                        nativeName: "Lëtzebuergesch",
                        iso6392T: "ltz",
                        iso6392B: "ltz"),
        IsoLanguageInfo(isoName: "Luba-Lulua",
                        nativeName: "Tshiluba",
                        iso6392T: "lua",
                        iso6392B: "lua"),
        IsoLanguageInfo(isoName: "Luba-Katanga",
                        nativeName: "Kiluba",
                        iso6392T: "lub",
                        iso6392B: "lub"),
        IsoLanguageInfo(isoName: "Ganda",
                        nativeName: "Luganda",
                        iso6392T: "lug",
                        iso6392B: "lug"),
        IsoLanguageInfo(isoName: "Luiseno",
                        nativeName: "Cham'teela",
                        iso6392T: "lui",
                        iso6392B: "lui"),
        IsoLanguageInfo(isoName: "Lunda",
                        nativeName: "Chilunda",
                        iso6392T: "lun",
                        iso6392B: "lun"),
        IsoLanguageInfo(isoName: "Luo (isoName: Kenya and Tanzania)",
                        nativeName: "Dholuo",
                        iso6392T: "luo",
                        iso6392B: "luo"),
        IsoLanguageInfo(isoName: "Lushai",
                        nativeName: "Mizo ṭawng",
                        iso6392T: "lus",
                        iso6392B: "lus"),
        IsoLanguageInfo(isoName: "Macedonian",
                        nativeName: "македонски јазик",
                        iso6392T: "mkd",
                        iso6392B: "mac"),
        IsoLanguageInfo(isoName: "Madurese",
                        nativeName: "Madhura",
                        iso6392T: "mad",
                        iso6392B: "mad"),
        IsoLanguageInfo(isoName: "Magahi",
                        nativeName: "मगही",
                        iso6392T: "mag",
                        iso6392B: "mag"),
        IsoLanguageInfo(isoName: "Marshallese",
                        nativeName: "Kajin M̧ajeļ",
                        iso6392T: "mah",
                        iso6392B: "mah"),
        IsoLanguageInfo(isoName: "Maithili",
                        nativeName: "मैथिली; মৈথিলী",
                        iso6392T: "mai",
                        iso6392B: "mai"),
        IsoLanguageInfo(isoName: "Makasar",
                        nativeName: "Basa Mangkasara' / ᨅᨔ ᨆᨀᨔᨑ",
                        iso6392T: "mak",
                        iso6392B: "mak"),
        IsoLanguageInfo(isoName: "Malayalam",
                        nativeName: "മലയാളം",
                        iso6392T: "mal",
                        iso6392B: "mal"),
        IsoLanguageInfo(isoName: "Mandingo",
                        nativeName: "Mandi'nka kango",
                        iso6392T: "man",
                        iso6392B: "man"),
        IsoLanguageInfo(isoName: "Maori",
                        nativeName: "Te Reo Māori",
                        iso6392T: "mri",
                        iso6392B: "mao"),
        IsoLanguageInfo(isoName: "Austronesian languages",
                        nativeName: "Austronesian languages",
                        iso6392T: "map",
                        iso6392B: "map"),
        IsoLanguageInfo(isoName: "Marathi",
                        nativeName: "मराठी",
                        iso6392T: "mar",
                        iso6392B: "mar"),
        IsoLanguageInfo(isoName: "Masai",
                        nativeName: "ɔl",
                        iso6392T: "mas",
                        iso6392B: "mas"),
        IsoLanguageInfo(isoName: "Malay",
                        nativeName: "Bahasa Melayu",
                        iso6392T: "msa",
                        iso6392B: "may"),
        IsoLanguageInfo(isoName: "Moksha",
                        nativeName: "мокшень кяль",
                        iso6392T: "mdf",
                        iso6392B: "mdf"),
        IsoLanguageInfo(isoName: "Mandar",
                        nativeName: "Mandar",
                        iso6392T: "mdr",
                        iso6392B: "mdr"),
        IsoLanguageInfo(isoName: "Mende",
                        nativeName: "Mɛnde yia",
                        iso6392T: "men",
                        iso6392B: "men"),
        IsoLanguageInfo(isoName: "Irish, Middle (isoName: 900–1200)",
                        nativeName: "Gaoidhealg",
                        iso6392T: "mga",
                        iso6392B: "mga"),
        IsoLanguageInfo(isoName: "Mi'kmaq; Micmac",
                        nativeName: "Míkmawísimk",
                        iso6392T: "mic",
                        iso6392B: "mic"),
        IsoLanguageInfo(isoName: "Minangkabau",
                        nativeName: "Baso Minang",
                        iso6392T: "min",
                        iso6392B: "min"),
        IsoLanguageInfo(isoName: "Uncoded languages",
                        nativeName: "Uncoded languages",
                        iso6392T: "mis",
                        iso6392B: "mis"),
        IsoLanguageInfo(isoName: "Mon-Khmer languages",
                        nativeName: "Mon-Khmer languages",
                        iso6392T: "mkh",
                        iso6392B: "mkh"),
        IsoLanguageInfo(isoName: "Malagasy",
                        nativeName: "Malagasy",
                        iso6392T: "mlg",
                        iso6392B: "mlg"),
        IsoLanguageInfo(isoName: "Maltese",
                        nativeName: "Malti",
                        iso6392T: "mlt",
                        iso6392B: "mlt"),
        IsoLanguageInfo(isoName: "Manchu",
                        nativeName: "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ",
                        iso6392T: "mnc",
                        iso6392B: "mnc"),
        IsoLanguageInfo(isoName: "Manipuri",
                        nativeName: "Manipuri",
                        iso6392T: "mni",
                        iso6392B: "mni"),
        IsoLanguageInfo(isoName: "Manobo languages",
                        nativeName: "Manobo languages",
                        iso6392T: "mno",
                        iso6392B: "mno"),
        IsoLanguageInfo(isoName: "Mohawk",
                        nativeName: "Kanien’kéha",
                        iso6392T: "moh",
                        iso6392B: "moh"),
        IsoLanguageInfo(isoName: "Mongolian",
                        nativeName: "монгол хэл; ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ",
                        iso6392T: "mon",
                        iso6392B: "mon"),
        IsoLanguageInfo(isoName: "Mossi",
                        nativeName: "Mooré",
                        iso6392T: "mos",
                        iso6392B: "mos"),
        IsoLanguageInfo(isoName: "Multiple languages",
                        nativeName: "Multiple languages",
                        iso6392T: "mul",
                        iso6392B: "mul"),
        IsoLanguageInfo(isoName: "Munda languages",
                        nativeName: "Munda languages",
                        iso6392T: "mun",
                        iso6392B: "mun"),
        IsoLanguageInfo(isoName: "Creek",
                        nativeName: "Mvskoke",
                        iso6392T: "mus",
                        iso6392B: "mus"),
        IsoLanguageInfo(isoName: "Mirandese",
                        nativeName: "mirandés; lhéngua mirandesa",
                        iso6392T: "mwl",
                        iso6392B: "mwl"),
        IsoLanguageInfo(isoName: "Marwari",
                        nativeName: "मारवाड़ी",
                        iso6392T: "mwr",
                        iso6392B: "mwr"),
        IsoLanguageInfo(isoName: "Mayan languages",
                        nativeName: "Mayan languages",
                        iso6392T: "myn",
                        iso6392B: "myn"),
        IsoLanguageInfo(isoName: "Erzya",
                        nativeName: "эрзянь кель",
                        iso6392T: "myv",
                        iso6392B: "myv"),
        IsoLanguageInfo(isoName: "Nahuatl languages",
                        nativeName: "Nahuatl languages",
                        iso6392T: "nah",
                        iso6392B: "nah"),
        IsoLanguageInfo(isoName: "North American Indian languages",
                        nativeName: "North American Indian languages",
                        iso6392T: "nai",
                        iso6392B: "nai"),
        IsoLanguageInfo(isoName: "Neapolitan",
                        nativeName: "napulitano",
                        iso6392T: "nap",
                        iso6392B: "nap"),
        IsoLanguageInfo(isoName: "Nauru",
                        nativeName: "dorerin Naoero",
                        iso6392T: "nau",
                        iso6392B: "nau"),
        IsoLanguageInfo(isoName: "Navajo; Navaho",
                        nativeName: "Diné bizaad; Naabeehó bizaad",
                        iso6392T: "nav",
                        iso6392B: "nav"),
        IsoLanguageInfo(isoName: "Ndebele, South; South Ndebele",
                        nativeName: "isiNdebele seSewula",
                        iso6392T: "nbl",
                        iso6392B: "nbl"),
        IsoLanguageInfo(isoName: "Ndebele, North; North Ndebele",
                        nativeName: "siNdebele saseNyakatho",
                        iso6392T: "nde",
                        iso6392B: "nde"),
        IsoLanguageInfo(isoName: "Ndonga",
                        nativeName: "ndonga",
                        iso6392T: "ndo",
                        iso6392B: "ndo"),
        IsoLanguageInfo(isoName: "Low German; Low Saxon; German, Low; Saxon, Low",
                        nativeName: "Plattdütsch; Plattdüütsch",
                        iso6392T: "nds",
                        iso6392B: "nds"),
        IsoLanguageInfo(isoName: "Nepali",
                        nativeName: "नेपाली भाषा",
                        iso6392T: "nep",
                        iso6392B: "nep"),
        IsoLanguageInfo(isoName: "Nepal Bhasa; Newari",
                        nativeName: "नेपाल भाषा; नेवाः भाय्",
                        iso6392T: "new",
                        iso6392B: "new"),
        IsoLanguageInfo(isoName: "Nias",
                        nativeName: "Li Niha",
                        iso6392T: "nia",
                        iso6392B: "nia"),
        IsoLanguageInfo(isoName: "Niger-Kordofanian languages",
                        nativeName: "Niger-Kordofanian languages",
                        iso6392T: "nic",
                        iso6392B: "nic"),
        IsoLanguageInfo(isoName: "Niuean",
                        nativeName: "ko e vagahau Niuē",
                        iso6392T: "niu",
                        iso6392B: "niu"),
        IsoLanguageInfo(isoName: "Norwegian Nynorsk; Nynorsk, Norwegian",
                        nativeName: "nynorsk",
                        iso6392T: "nno",
                        iso6392B: "nno"),
        IsoLanguageInfo(isoName: "Bokmål, Norwegian; Norwegian Bokmål",
                        nativeName: "bokmål",
                        iso6392T: "nob",
                        iso6392B: "nob"),
        IsoLanguageInfo(isoName: "Nogai",
                        nativeName: "Ногай тили",
                        iso6392T: "nog",
                        iso6392B: "nog"),
        IsoLanguageInfo(isoName: "Norse, Old",
                        nativeName: "Dǫnsk tunga; Norrœnt mál",
                        iso6392T: "non",
                        iso6392B: "non"),
        IsoLanguageInfo(isoName: "Norwegian",
                        nativeName: "norsk",
                        iso6392T: "nor",
                        iso6392B: "nor"),
        IsoLanguageInfo(isoName: "N'Ko",
                        nativeName: "N'Ko",
                        iso6392T: "nqo",
                        iso6392B: "nqo"),
        IsoLanguageInfo(isoName: "Pedi; Sepedi; Northern Sotho",
                        nativeName: "Sesotho sa Leboa",
                        iso6392T: "nso",
                        iso6392B: "nso"),
        IsoLanguageInfo(isoName: "Nubian languages",
                        nativeName: "لغات نوبية",
                        iso6392T: "nub",
                        iso6392B: "nub"),
        IsoLanguageInfo(isoName: "Classical Newari; Old Newari; Classical Nepal Bhasa",
                        nativeName: "पुलां भाय्; पुलाङु नेपाल भाय्",
                        iso6392T: "nwc",
                        iso6392B: "nwc"),
        IsoLanguageInfo(isoName: "Chichewa; Chewa; Nyanja",
                        nativeName: "Chichewa; Chinyanja",
                        iso6392T: "nya",
                        iso6392B: "nya"),
        IsoLanguageInfo(isoName: "Nyamwezi",
                        nativeName: "Nyamwezi",
                        iso6392T: "nym",
                        iso6392B: "nym"),
        IsoLanguageInfo(isoName: "Nyankole",
                        nativeName: "Nyankole",
                        iso6392T: "nyn",
                        iso6392B: "nyn"),
        IsoLanguageInfo(isoName: "Nyoro",
                        nativeName: "Runyoro",
                        iso6392T: "nyo",
                        iso6392B: "nyo"),
        IsoLanguageInfo(isoName: "Nzima",
                        nativeName: "Nzima",
                        iso6392T: "nzi",
                        iso6392B: "nzi"),
        IsoLanguageInfo(isoName: "Occitan (isoName: post 1500); Provençal",
                        nativeName: "occitan; lenga d'òc; provençal",
                        iso6392T: "oci",
                        iso6392B: "oci"),
        IsoLanguageInfo(isoName: "Ojibwa",
                        nativeName: "Ojibwa",
                        iso6392T: "oji",
                        iso6392B: "oji"),
        IsoLanguageInfo(isoName: "Oriya",
                        nativeName: "ଓଡ଼ିଆ",
                        iso6392T: "ori",
                        iso6392B: "ori"),
        IsoLanguageInfo(isoName: "Oromo",
                        nativeName: "Afaan Oromoo",
                        iso6392T: "orm",
                        iso6392B: "orm"),
        IsoLanguageInfo(isoName: "Osage",
                        nativeName: "Wazhazhe ie / 𐓏𐓘𐓻𐓘𐓻𐓟 𐒻𐓟",
                        iso6392T: "osa",
                        iso6392B: "osa"),
        IsoLanguageInfo(isoName: "Ossetian; Ossetic",
                        nativeName: "Ирон æвзаг",
                        iso6392T: "oss",
                        iso6392B: "oss"),
        IsoLanguageInfo(isoName: "Turkish, Ottoman (isoName: 1500–1928)",
                        nativeName: "لسان عثمانى / lisân-ı Osmânî",
                        iso6392T: "ota",
                        iso6392B: "ota"),
        IsoLanguageInfo(isoName: "Otomian languages",
                        nativeName: "Otomian languages",
                        iso6392T: "oto",
                        iso6392B: "oto"),
        IsoLanguageInfo(isoName: "Papuan languages",
                        nativeName: "Papuan languages",
                        iso6392T: "paa",
                        iso6392B: "paa"),
        IsoLanguageInfo(isoName: "Pangasinan",
                        nativeName: "Salitan Pangasinan",
                        iso6392T: "pag",
                        iso6392B: "pag"),
        IsoLanguageInfo(isoName: "Pahlavi",
                        nativeName: "Pārsīk; Pārsīg",
                        iso6392T: "pal",
                        iso6392B: "pal"),
        IsoLanguageInfo(isoName: "Pampanga; Kapampangan",
                        nativeName: "Amánung Kapampangan; Amánung Sísuan",
                        iso6392T: "pam",
                        iso6392B: "pam"),
        IsoLanguageInfo(isoName: "Panjabi; Punjabi",
                        nativeName: "ਪੰਜਾਬੀ / پنجابی",
                        iso6392T: "pan",
                        iso6392B: "pan"),
        IsoLanguageInfo(isoName: "Papiamento",
                        nativeName: "Papiamentu",
                        iso6392T: "pap",
                        iso6392B: "pap"),
        IsoLanguageInfo(isoName: "Palauan",
                        nativeName: "a tekoi er a Belau",
                        iso6392T: "pau",
                        iso6392B: "pau"),
        IsoLanguageInfo(isoName: "Persian, Old (isoName: ca. 600–400 B.C.)",
                        nativeName: "Persian, Old (isoName: ca. 600–400 B.C.)",
                        iso6392T: "peo",
                        iso6392B: "peo"),
        IsoLanguageInfo(isoName: "Philippine languages",
                        nativeName: "Philippine languages",
                        iso6392T: "phi",
                        iso6392B: "phi"),
        IsoLanguageInfo(isoName: "Phoenician",
                        nativeName: "𐤃𐤁𐤓𐤉𐤌 𐤊𐤍𐤏𐤍𐤉𐤌",
                        iso6392T: "phn",
                        iso6392B: "phn"),
        IsoLanguageInfo(isoName: "Pali",
                        nativeName: "Pāli",
                        iso6392T: "pli",
                        iso6392B: "pli"),
        IsoLanguageInfo(isoName: "Polish",
                        nativeName: "Język polski",
                        iso6392T: "pol",
                        iso6392B: "pol"),
        IsoLanguageInfo(isoName: "Pohnpeian",
                        nativeName: "Pohnpeian",
                        iso6392T: "pon",
                        iso6392B: "pon"),
        IsoLanguageInfo(isoName: "Portuguese",
                        nativeName: "português",
                        iso6392T: "por",
                        iso6392B: "por"),
        IsoLanguageInfo(isoName: "Prakrit languages",
                        nativeName: "Prakrit languages",
                        iso6392T: "pra",
                        iso6392B: "pra"),
        IsoLanguageInfo(isoName: "Provençal, Old (isoName: to 1500); Old Occitan (isoName: to 1500)",
                        nativeName: "Provençal, Old (isoName: to 1500); Old Occitan (isoName: to 1500)",
                        iso6392T: "pro",
                        iso6392B: "pro"),
        IsoLanguageInfo(isoName: "Pushto; Pashto",
                        nativeName: "پښتو",
                        iso6392T: "pus",
                        iso6392B: "pus"),
        IsoLanguageInfo(isoName: "Quechua",
                        nativeName: "Runa simi; kichwa simi; Nuna shimi",
                        iso6392T: "que",
                        iso6392B: "que"),
        IsoLanguageInfo(isoName: "Rajasthani",
                        nativeName: "राजस्थानी",
                        iso6392T: "raj",
                        iso6392B: "raj"),
        IsoLanguageInfo(isoName: "Rapanui",
                        nativeName: "Vananga rapa nui",
                        iso6392T: "rap",
                        iso6392B: "rap"),
        IsoLanguageInfo(isoName: "Rarotongan; Cook Islands Maori",
                        nativeName: "Māori Kūki 'Āirani",
                        iso6392T: "rar",
                        iso6392B: "rar"),
        IsoLanguageInfo(isoName: "Romance languages",
                        nativeName: "Romance languages",
                        iso6392T: "roa",
                        iso6392B: "roa"),
        IsoLanguageInfo(isoName: "Romansh",
                        nativeName: "Rumantsch; Rumàntsch; Romauntsch; Romontsch",
                        iso6392T: "roh",
                        iso6392B: "roh"),
        IsoLanguageInfo(isoName: "Romany",
                        nativeName: "romani čhib",
                        iso6392T: "rom",
                        iso6392B: "rom"),
        IsoLanguageInfo(isoName: "Romanian; Moldavian; Moldovan",
                        nativeName: "limba română",
                        iso6392T: "ron",
                        iso6392B: "rum"),
        IsoLanguageInfo(isoName: "Rundi",
                        nativeName: "Ikirundi",
                        iso6392T: "run",
                        iso6392B: "run"),
        IsoLanguageInfo(isoName: "Aromanian; Arumanian; Macedo-Romanian",
                        nativeName: "armãneashce; armãneashti; rrãmãneshti",
                        iso6392T: "rup",
                        iso6392B: "rup"),
        IsoLanguageInfo(isoName: "Russian",
                        nativeName: "русский язык",
                        iso6392T: "rus",
                        iso6392B: "rus"),
        IsoLanguageInfo(isoName: "Sandawe",
                        nativeName: "Sandaweeki",
                        iso6392T: "sad",
                        iso6392B: "sad"),
        IsoLanguageInfo(isoName: "Sango",
                        nativeName: "yângâ tî sängö",
                        iso6392T: "sag",
                        iso6392B: "sag"),
        IsoLanguageInfo(isoName: "Yakut",
                        nativeName: "Сахалыы",
                        iso6392T: "sah",
                        iso6392B: "sah"),
        IsoLanguageInfo(isoName: "South American Indian (isoName: Other)",
                        nativeName: "South American Indian (isoName: Other)",
                        iso6392T: "sai",
                        iso6392B: "sai"),
        IsoLanguageInfo(isoName: "Salishan languages",
                        nativeName: "Salishan languages",
                        iso6392T: "sal",
                        iso6392B: "sal"),
        IsoLanguageInfo(isoName: "Samaritan Aramaic",
                        nativeName: "ארמית",
                        iso6392T: "sam",
                        iso6392B: "sam"),
        IsoLanguageInfo(isoName: "Sanskrit",
                        nativeName: "Sanskrit",
                        iso6392T: "san",
                        iso6392B: "san"),
        IsoLanguageInfo(isoName: "Sasak",
                        nativeName: "Sasak",
                        iso6392T: "sas",
                        iso6392B: "sas"),
        IsoLanguageInfo(isoName: "Santali",
                        nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
                        iso6392T: "sat",
                        iso6392B: "sat"),
        IsoLanguageInfo(isoName: "Sicilian",
                        nativeName: "Sicilianu",
                        iso6392T: "scn",
                        iso6392B: "scn"),
        IsoLanguageInfo(isoName: "Scots",
                        nativeName: "Braid Scots; Lallans",
                        iso6392T: "sco",
                        iso6392B: "sco"),
        IsoLanguageInfo(isoName: "Selkup",
                        nativeName: "Selkup",
                        iso6392T: "sel",
                        iso6392B: "sel"),
        IsoLanguageInfo(isoName: "Semitic languages",
                        nativeName: "Semitic languages",
                        iso6392T: "sem",
                        iso6392B: "sem"),
        IsoLanguageInfo(isoName: "Irish, Old (isoName: to 900)",
                        nativeName: "Goídelc",
                        iso6392T: "sga",
                        iso6392B: "sga"),
        IsoLanguageInfo(isoName: "Sign Languages",
                        nativeName: "Sign Languages",
                        iso6392T: "sgn",
                        iso6392B: "sgn"),
        IsoLanguageInfo(isoName: "Shan",
                        nativeName: "ၵႂၢမ်းတႆးယႂ်",
                        iso6392T: "shn",
                        iso6392B: "shn"),
        IsoLanguageInfo(isoName: "Sidamo",
                        nativeName: "Sidaamu Afoo",
                        iso6392T: "sid",
                        iso6392B: "sid"),
        IsoLanguageInfo(isoName: "Sinhala; Sinhalese",
                        nativeName: "සිංහල",
                        iso6392T: "sin",
                        iso6392B: "sin"),
        IsoLanguageInfo(isoName: "Siouan languages",
                        nativeName: "Siouan languages",
                        iso6392T: "sio",
                        iso6392B: "sio"),
        IsoLanguageInfo(isoName: "Sino-Tibetan languages",
                        nativeName: "Sino-Tibetan languages",
                        iso6392T: "sit",
                        iso6392B: "sit"),
        IsoLanguageInfo(isoName: "Slavic languages",
                        nativeName: "Slavic languages",
                        iso6392T: "sla",
                        iso6392B: "sla"),
        IsoLanguageInfo(isoName: "Slovak",
                        nativeName: "slovenčina; slovenský jazyk",
                        iso6392T: "slk",
                        iso6392B: "slo"),
        IsoLanguageInfo(isoName: "Slovenian",
                        nativeName: "slovenski jezik; slovenščina",
                        iso6392T: "slv",
                        iso6392B: "slv"),
        IsoLanguageInfo(isoName: "Southern Sami",
                        nativeName: "Åarjelsaemien gïele",
                        iso6392T: "sma",
                        iso6392B: "sma"),
        IsoLanguageInfo(isoName: "Northern Sami",
                        nativeName: "davvisámegiella",
                        iso6392T: "sme",
                        iso6392B: "sme"),
        IsoLanguageInfo(isoName: "Sami languages",
                        nativeName: "Sami languages",
                        iso6392T: "smi",
                        iso6392B: "smi"),
        IsoLanguageInfo(isoName: "Lule Sami",
                        nativeName: "julevsámegiella",
                        iso6392T: "smj",
                        iso6392B: "smj"),
        IsoLanguageInfo(isoName: "Inari Sami",
                        nativeName: "anarâškielâ",
                        iso6392T: "smn",
                        iso6392B: "smn"),
        IsoLanguageInfo(isoName: "Samoan",
                        nativeName: "Gagana faʻa Sāmoa",
                        iso6392T: "smo",
                        iso6392B: "smo"),
        IsoLanguageInfo(isoName: "Skolt Sami",
                        nativeName: "sääʹmǩiõll",
                        iso6392T: "sms",
                        iso6392B: "sms"),
        IsoLanguageInfo(isoName: "Shona",
                        nativeName: "chiShona",
                        iso6392T: "sna",
                        iso6392B: "sna"),
        IsoLanguageInfo(isoName: "Sindhi",
                        nativeName: "سنڌي / सिन्धी / ਸਿੰਧੀ",
                        iso6392T: "snd",
                        iso6392B: "snd"),
        IsoLanguageInfo(isoName: "Soninke",
                        nativeName: "Sooninkanxanne",
                        iso6392T: "snk",
                        iso6392B: "snk"),
        IsoLanguageInfo(isoName: "Sogdian",
                        nativeName: "Sogdian",
                        iso6392T: "sog",
                        iso6392B: "sog"),
        IsoLanguageInfo(isoName: "Somali",
                        nativeName: "af Soomaali",
                        iso6392T: "som",
                        iso6392B: "som"),
        IsoLanguageInfo(isoName: "Songhai languages",
                        nativeName: "Songhai languages",
                        iso6392T: "son",
                        iso6392B: "son"),
        IsoLanguageInfo(isoName: "Sotho, Southern",
                        nativeName: "Sesotho [southern]",
                        iso6392T: "sot",
                        iso6392B: "sot"),
        IsoLanguageInfo(isoName: "Spanish; Castilian",
                        nativeName: "español; castellano",
                        iso6392T: "spa",
                        iso6392B: "spa"),
        IsoLanguageInfo(isoName: "Sardinian",
                        nativeName: "sardu; limba sarda; lingua sarda",
                        iso6392T: "srd",
                        iso6392B: "srd"),
        IsoLanguageInfo(isoName: "Sranan Tongo",
                        nativeName: "Sranan Tongo",
                        iso6392T: "srn",
                        iso6392B: "srn"),
        IsoLanguageInfo(isoName: "Serbian",
                        nativeName: "српски / srpski",
                        iso6392T: "srp",
                        iso6392B: "srp"),
        IsoLanguageInfo(isoName: "Serer",
                        nativeName: "Seereer",
                        iso6392T: "srr",
                        iso6392B: "srr"),
        IsoLanguageInfo(isoName: "Nilo-Saharan languages",
                        nativeName: "Nilo-Saharan languages",
                        iso6392T: "ssa",
                        iso6392B: "ssa"),
        IsoLanguageInfo(isoName: "Swati",
                        nativeName: "siSwati",
                        iso6392T: "ssw",
                        iso6392B: "ssw"),
        IsoLanguageInfo(isoName: "Sukuma",
                        nativeName: "Kɪsukuma",
                        iso6392T: "suk",
                        iso6392B: "suk"),
        IsoLanguageInfo(isoName: "Sundanese",
                        nativeName: "ᮘᮞ ᮞᮥᮔ᮪ᮓ / Basa Sunda",
                        iso6392T: "sun",
                        iso6392B: "sun"),
        IsoLanguageInfo(isoName: "Susu",
                        nativeName: "Sosoxui",
                        iso6392T: "sus",
                        iso6392B: "sus"),
        IsoLanguageInfo(isoName: "Sumerian",
                        nativeName: "𒅴𒂠",
                        iso6392T: "sux",
                        iso6392B: "sux"),
        IsoLanguageInfo(isoName: "Swahili",
                        nativeName: "Kiswahili",
                        iso6392T: "swa",
                        iso6392B: "swa"),
        IsoLanguageInfo(isoName: "Swedish",
                        nativeName: "svenska",
                        iso6392T: "swe",
                        iso6392B: "swe"),
        IsoLanguageInfo(isoName: "Classical Syriac",
                        nativeName: "Classical Syriac",
                        iso6392T: "syc",
                        iso6392B: "syc"),
        IsoLanguageInfo(isoName: "Syriac",
                        nativeName: "ܠܫܢܐ ܣܘܪܝܝܐ",
                        iso6392T: "syr",
                        iso6392B: "syr"),
        IsoLanguageInfo(isoName: "Tahitian",
                        nativeName: "Reo Tahiti; Reo Mā'ohi",
                        iso6392T: "tah",
                        iso6392B: "tah"),
        IsoLanguageInfo(isoName: "Tai languages",
                        nativeName: "ภาษาไท; ภาษาไต",
                        iso6392T: "tai",
                        iso6392B: "tai"),
        IsoLanguageInfo(isoName: "Tamil",
                        nativeName: "தமிழ்",
                        iso6392T: "tam",
                        iso6392B: "tam"),
        IsoLanguageInfo(isoName: "Tatar",
                        nativeName: "татар теле / tatar tele / تاتار",
                        iso6392T: "tat",
                        iso6392B: "tat"),
        IsoLanguageInfo(isoName: "Telugu",
                        nativeName: "తెలుగు",
                        iso6392T: "tel",
                        iso6392B: "tel"),
        IsoLanguageInfo(isoName: "Timne",
                        nativeName: "KʌThemnɛ",
                        iso6392T: "tem",
                        iso6392B: "tem"),
        IsoLanguageInfo(isoName: "Tereno",
                        nativeName: "Terêna",
                        iso6392T: "ter",
                        iso6392B: "ter"),
        IsoLanguageInfo(isoName: "Tetum",
                        nativeName: "Lia-Tetun",
                        iso6392T: "tet",
                        iso6392B: "tet"),
        IsoLanguageInfo(isoName: "Tajik",
                        nativeName: "тоҷикӣ / tojikī",
                        iso6392T: "tgk",
                        iso6392B: "tgk"),
        IsoLanguageInfo(isoName: "Tagalog",
                        nativeName: "Wikang Tagalog",
                        iso6392T: "tgl",
                        iso6392B: "tgl"),
        IsoLanguageInfo(isoName: "Thai",
                        nativeName: "ภาษาไทย",
                        iso6392T: "tha",
                        iso6392B: "tha"),
        IsoLanguageInfo(isoName: "Tigre",
                        nativeName: "ትግረ; ትግሬ; ኻሳ; ትግራይት",
                        iso6392T: "tig",
                        iso6392B: "tig"),
        IsoLanguageInfo(isoName: "Tigrinya",
                        nativeName: "ትግርኛ",
                        iso6392T: "tir",
                        iso6392B: "tir"),
        IsoLanguageInfo(isoName: "Tiv",
                        nativeName: "Tiv",
                        iso6392T: "tiv",
                        iso6392B: "tiv"),
        IsoLanguageInfo(isoName: "Tokelau",
                        nativeName: "Tokelau",
                        iso6392T: "tkl",
                        iso6392B: "tkl"),
        IsoLanguageInfo(isoName: "Klingon; tlhIngan-Hol",
                        nativeName: "Klingon; tlhIngan-Hol",
                        iso6392T: "tlh",
                        iso6392B: "tlh"),
        IsoLanguageInfo(isoName: "Tlingit",
                        nativeName: "Lingít",
                        iso6392T: "tli",
                        iso6392B: "tli"),
        IsoLanguageInfo(isoName: "Tamashek",
                        nativeName: "Tamashek",
                        iso6392T: "tmh",
                        iso6392B: "tmh"),
        IsoLanguageInfo(isoName: "Tonga (isoName: Nyasa)",
                        nativeName: "chiTonga",
                        iso6392T: "tog",
                        iso6392B: "tog"),
        IsoLanguageInfo(isoName: "Tonga (isoName: Tonga Islands)",
                        nativeName: "lea faka-Tonga",
                        iso6392T: "ton",
                        iso6392B: "ton"),
        IsoLanguageInfo(isoName: "Tok Pisin",
                        nativeName: "Tok Pisin",
                        iso6392T: "tpi",
                        iso6392B: "tpi"),
        IsoLanguageInfo(isoName: "Tsimshian",
                        nativeName: "Tsimshian",
                        iso6392T: "tsi",
                        iso6392B: "tsi"),
        IsoLanguageInfo(isoName: "Tswana",
                        nativeName: "Setswana",
                        iso6392T: "tsn",
                        iso6392B: "tsn"),
        IsoLanguageInfo(isoName: "Tsonga",
                        nativeName: "Xitsonga",
                        iso6392T: "tso",
                        iso6392B: "tso"),
        IsoLanguageInfo(isoName: "Turkmen",
                        nativeName: "Türkmençe / Түркменче / تورکمن تیلی تورکمنچ; türkmen dili / түркмен дили",
                        iso6392T: "tuk",
                        iso6392B: "tuk"),
        IsoLanguageInfo(isoName: "Tumbuka",
                        nativeName: "chiTumbuka",
                        iso6392T: "tum",
                        iso6392B: "tum"),
        IsoLanguageInfo(isoName: "Tupi languages",
                        nativeName: "Tupi languages",
                        iso6392T: "tup",
                        iso6392B: "tup"),
        IsoLanguageInfo(isoName: "Turkish",
                        nativeName: "Türkçe",
                        iso6392T: "tur",
                        iso6392B: "tur"),
        IsoLanguageInfo(isoName: "Altaic languages",
                        nativeName: "Altaic languages",
                        iso6392T: "tut",
                        iso6392B: "tut"),
        IsoLanguageInfo(isoName: "Tuvalu",
                        nativeName: "Te Ggana Tuuvalu; Te Gagana Tuuvalu",
                        iso6392T: "tvl",
                        iso6392B: "tvl"),
        IsoLanguageInfo(isoName: "Twi",
                        nativeName: "Twi",
                        iso6392T: "twi",
                        iso6392B: "twi"),
        IsoLanguageInfo(isoName: "Tuvinian",
                        nativeName: "тыва дыл",
                        iso6392T: "tyv",
                        iso6392B: "tyv"),
        IsoLanguageInfo(isoName: "Udmurt",
                        nativeName: "удмурт кыл",
                        iso6392T: "udm",
                        iso6392B: "udm"),
        IsoLanguageInfo(isoName: "Ugaritic",
                        nativeName: "Ugaritic",
                        iso6392T: "uga",
                        iso6392B: "uga"),
        IsoLanguageInfo(isoName: "Uighur; Uyghur",
                        nativeName: "ئۇيغۇرچە ; ئۇيغۇر تىلى",
                        iso6392T: "uig",
                        iso6392B: "uig"),
        IsoLanguageInfo(isoName: "Ukrainian",
                        nativeName: "українська мова",
                        iso6392T: "ukr",
                        iso6392B: "ukr"),
        IsoLanguageInfo(isoName: "Umbundu",
                        nativeName: "Úmbúndú",
                        iso6392T: "umb",
                        iso6392B: "umb"),
        IsoLanguageInfo(isoName: "Undetermined",
                        nativeName: "Undetermined",
                        iso6392T: "und",
                        iso6392B: "und"),
        IsoLanguageInfo(isoName: "Urdu",
                        nativeName: "اُردُو",
                        iso6392T: "urd",
                        iso6392B: "urd"),
        IsoLanguageInfo(isoName: "Uzbek",
                        nativeName: "Oʻzbekcha / ўзбекча / ئوزبېچه; oʻzbek tili / ўзбек тили / ئوبېک تیلی",
                        iso6392T: "uzb",
                        iso6392B: "uzb"),
        IsoLanguageInfo(isoName: "Vai",
                        nativeName: "ꕙꔤ",
                        iso6392T: "vai",
                        iso6392B: "vai"),
        IsoLanguageInfo(isoName: "Venda",
                        nativeName: "Tshivenḓa",
                        iso6392T: "ven",
                        iso6392B: "ven"),
        IsoLanguageInfo(isoName: "Vietnamese",
                        nativeName: "Tiếng Việt",
                        iso6392T: "vie",
                        iso6392B: "vie"),
        IsoLanguageInfo(isoName: "Volapük",
                        nativeName: "Volapük",
                        iso6392T: "vol",
                        iso6392B: "vol"),
        IsoLanguageInfo(isoName: "Votic",
                        nativeName: "vađđa ceeli",
                        iso6392T: "vot",
                        iso6392B: "vot"),
        IsoLanguageInfo(isoName: "Wakashan languages",
                        nativeName: "Wakashan languages",
                        iso6392T: "wak",
                        iso6392B: "wak"),
        IsoLanguageInfo(isoName: "Wolaitta; Wolaytta",
                        nativeName: "Wolaitta; Wolaytta",
                        iso6392T: "wal",
                        iso6392B: "wal"),
        IsoLanguageInfo(isoName: "Waray",
                        nativeName: "Winaray; Samareño; Lineyte-Samarnon; Binisayâ nga Winaray; Binisayâ nga Samar-Leyte; “Binisayâ nga Waray”",
                        iso6392T: "war",
                        iso6392B: "war"),
        IsoLanguageInfo(isoName: "Washo",
                        nativeName: "wá:šiw ʔítlu",
                        iso6392T: "was",
                        iso6392B: "was"),
        IsoLanguageInfo(isoName: "Sorbian languages",
                        nativeName: "Serbsce / Serbski",
                        iso6392T: "wen",
                        iso6392B: "wen"),
        IsoLanguageInfo(isoName: "Walloon",
                        nativeName: "Walon",
                        iso6392T: "wln",
                        iso6392B: "wln"),
        IsoLanguageInfo(isoName: "Wolof",
                        nativeName: "Wolof",
                        iso6392T: "wol",
                        iso6392B: "wol"),
        IsoLanguageInfo(isoName: "Kalmyk; Oirat",
                        nativeName: "Хальмг келн / Xaľmg keln",
                        iso6392T: "xal",
                        iso6392B: "xal"),
        IsoLanguageInfo(isoName: "Xhosa",
                        nativeName: "isiXhosa",
                        iso6392T: "xho",
                        iso6392B: "xho"),
        IsoLanguageInfo(isoName: "Yao",
                        nativeName: "Yao",
                        iso6392T: "yao",
                        iso6392B: "yao"),
        IsoLanguageInfo(isoName: "Yapese",
                        nativeName: "Yapese",
                        iso6392T: "yap",
                        iso6392B: "yap"),
        IsoLanguageInfo(isoName: "Yiddish",
                        nativeName: "ייִדיש; יידיש; אידיש",
                        iso6392T: "yid",
                        iso6392B: "yid"),
        IsoLanguageInfo(isoName: "Yoruba",
                        nativeName: "èdè Yorùbá",
                        iso6392T: "yor",
                        iso6392B: "yor"),
        IsoLanguageInfo(isoName: "Yupik languages",
                        nativeName: "Yupik languages",
                        iso6392T: "ypk",
                        iso6392B: "ypk"),
        IsoLanguageInfo(isoName: "Zapotec",
                        nativeName: "Diidxazá",
                        iso6392T: "zap",
                        iso6392B: "zap"),
        IsoLanguageInfo(isoName: "Blissymbols; Blissymbolics; Bliss",
                        nativeName: "Blissymbols; Blissymbolics; Bliss",
                        iso6392T: "zbl",
                        iso6392B: "zbl"),
        IsoLanguageInfo(isoName: "Zenaga",
                        nativeName: "Tuḍḍungiyya",
                        iso6392T: "zen",
                        iso6392B: "zen"),
        IsoLanguageInfo(isoName: "Standard Moroccan Tamazight",
                        nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ",
                        iso6392T: "zgh",
                        iso6392B: "zgh"),
        IsoLanguageInfo(isoName: "Zhuang; Chuang",
                        nativeName: "Vahcuengh / 話僮",
                        iso6392T: "zha",
                        iso6392B: "zha"),
        IsoLanguageInfo(isoName: "Zande languages",
                        nativeName: "Zande languages",
                        iso6392T: "znd",
                        iso6392B: "znd"),
        IsoLanguageInfo(isoName: "Zulu",
                        nativeName: "isiZulu",
                        iso6392T: "zul",
                        iso6392B: "zul"),
        IsoLanguageInfo(isoName: "Zuni",
                        nativeName: "Shiwi'ma",
                        iso6392T: "zun",
                        iso6392B: "zun"),
        IsoLanguageInfo(isoName: "No linguistic content; Not applicable",
                        nativeName: "No linguistic content; Not applicable",
                        iso6392T: "zxx",
                        iso6392B: "zxx"),
        IsoLanguageInfo(isoName: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
                        nativeName: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
                        iso6392T: "zza",
                        iso6392B: "zza")
    ]
}
